#!/bin/bash
#
# Copyright 2004-2014 The Kuali Foundation
#
# Licensed under the Educational Community License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.opensource.org/licenses/ecl2.php
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function check_args {
  check_not_blank DOMAIN $DOMAIN
  check_not_blank SUBDOMAIN $SUBDOMAIN
  check_not_blank PACKAGES $PACKAGES
}

function configure_basics {
  echo "configure    -> basics"
  COMMAND="/mnt/${project.artifactId}/${project.groupId.path}/${project.artifactId}/ubuntu/12.04/common/configurebasics -p \"$PACKAGES\""
  echo "$COMMAND"
  SSH="ssh root@$FQDN "$COMMAND""
  execute_quietly "$SSH"
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/../common/functions.sh

usage() { echo "Usage: $ME [-h] [-q] [-p packages] [-d kuali.org] subdomain" 1>&2; exit 1; }

DOMAIN=kuali.org
PACKAGES="zip unzip ntp git"
QUIET=false
while getopts hqd:p: flag; do
  case $flag in
    h)
      usage;
      ;;
    q)
      QUIET="true";
      ;;
    d)
      DOMAIN="$OPTARG"
      ;;
    p)
      PACKAGES="$OPTARG"
      ;;
    ?)
      usage;
      exit;
      ;;
  esac
done

shift $(( OPTIND - 1 ));

SUBDOMAIN=$1

check_args

FQDN=$SUBDOMAIN.$DOMAIN

# ec2-107-22-110-181.compute-1.amazonaws.com
configure_basics