#!/bin/bash
#
# Copyright 2004-2014 The Kuali Foundation
#
# Licensed under the Educational Community License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.opensource.org/licenses/ecl2.php
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function show_usage {
  echo requires NEXUS_PASSWORD ZIP_PASSWORD SUBDOMAIN JDK TOMCAT MAX_HEAP MAX_PERM
  echo usage: appserver.sh ssl_password nexus_password subdomain jdk7/jdk6 tomcat7/tomcat6 max_heap max_perm [quiet]
  exit 1
}

function check_args {
  check_not_blank NEXUS_PASSWORD $NEXUS_PASSWORD
  check_not_blank ZIP_PASSWORD $ZIP_PASSWORD
  check_not_blank SUBDOMAIN $SUBDOMAIN
  check_not_blank JDK $JDK
  check_not_blank TOMCAT $TOMCAT
  check_not_blank MAX_HEAP $MAX_HEAP
  check_not_blank MAX_PERM $MAX_PERM
}

function configure_application_server {
  echo "configure -> $FQDN :: appserver"
  source installers.sh
  TOMCAT="$MODULES/common/install_tomcat.sh $ZIP_PASSWORD $DOMAIN $BASEDIR $TOMCAT $JDK $MAX_HEAP $MAX_PERM $QUIET"
  SSH="$BASICS; $JAVA; $DNS; $TOMCAT"
  ssh root@$FQDN "$SSH"
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
source $MY_DIR/../common/functions.sh

usage() { echo "Usage: $ME [-h] [-q] subdomain tomcat6/tomcat7 jdk6/jdk7 password" 1>&2; exit 1; }

source $MY_DIR/../common/functions.sh

echo $(date)

QUIET=false
MAX_HEAP=5g
MAX_PERM=256m
DOMAIN=kuali.org
MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=256m"

ARGS=$(getopt --options hq --longoptions "help,quiet,maxheap:,maxperm:,domain:,mavenopts:" --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -q|--quiet)
      QUIET="true";
      shift;
      ;;
    --maxheap)
      shift;
      MAX_HEAP="$1";
      shift;
      ;;
    --maxperm)
      shift;
      MAX_PERM="$1";
      shift;
      ;;
    --domain)
      shift;
      DOMAIN="$1";
      shift;
      ;;
    --mavenopts)
      shift;
      MAVEN_OPTS="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done

TOMCAT=$1
JDK=$2
GPG_PASSPHRASE=$3

# Make sure we have what we need
check_args

# import bootstrap variables/functions
source bootstrap.sh $SUBDOMAIN

echo "configure -> $FQDN"
enable_root_ssh
publish_module
configure_application_server

echo $(date)
