#!/bin/bash
#
# Copyright 2004-2014 The Kuali Foundation
#
# Licensed under the Educational Community License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.opensource.org/licenses/ecl2.php
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function check_args {
  check_not_blank SUBDOMAIN $SUBDOMAIN
  check_not_blank TOMCAT $TOMCAT
  check_not_blank JDK $JDK
  check_not_blank MAX_HEAP $MAX_HEAP
  check_not_blank MAX_PERM $MAX_PERM
  check_not_blank GPG_PASSPHRASE $GPG_PASSPHRASE
}

function configure_application_server {
  echo "configure -> $FQDN :: appserver"
  source installers.sh
  TOMCAT="$MODULES/common/installtomcat $ZIP_PASSWORD $DOMAIN $BASEDIR $TOMCAT $JDK $MAX_HEAP $MAX_PERM $QUIET"
  SSH="$BASICS; $JAVA; $DNS; $TOMCAT"
  ssh root@$FQDN "$SSH"
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
source $MY_DIR/../common/functions.sh
source $MY_DIR/../common/tomcatargs.sh

exit 1

# import bootstrap variables/functions
source $MY_DIR/bootstrap.sh $SUBDOMAIN

echo "configure -> $FQDN"
enable_root_ssh
publish_module
configure_application_server

echo $(date)
