#!/bin/bash
#
# Copyright 2004-2014 The Kuali Foundation
#
# Licensed under the Educational Community License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.opensource.org/licenses/ecl2.php
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function publish_module { 
  LOCAL="$HOME/.m2/repository/${project.groupId.path}/${project.artifactId}/${project.version}/${project.artifactId}-${project.version}.jar"
  DIR=/mnt/${project.artifactId}
  FILE=/mnt/${project.artifactId}.jar
  REMOTE=root@$FQDN:$FILE
  CMD1="rm -rf $DIR"
  CMD2="apt-get install unzip -y"
  CMD3="unzip $FILE -d $DIR"
  CMD4="chmod -R 755 $DIR"
  CMDS="$CMD1; $CMD2; $CMD3; $CMD4"
  echo "publish   -> $REMOTE"
  execute_quietly "scp $LOCAL $REMOTE"
  execute_quietly "ssh root@$FQDN "$CMDS""
}

function check_args {
  check_not_blank DOMAIN $DOMAIN
  check_not_blank SUBDOMAIN $SUBDOMAIN
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/../common/functions.sh

usage() { echo "Usage: $ME [-h] [-q] [-d kuali.org] subdomain" 1>&2; exit 1; }

DOMAIN=kuali.org

QUIET=false
while getopts hqd: flag; do
  case $flag in
    h)
      usage;
      ;;
    q)
      QUIET="true";
      ;;
    d)
      DOMAIN="$OPTARG"
      ;;
    ?)
      usage;
      exit;
      ;;
  esac
done

shift $(( OPTIND - 1 ));

SUBDOMAIN=$1

check_args

# ec2-107-22-110-181.compute-1.amazonaws.com

FQDN=$SUBDOMAIN.$DOMAIN

publish_module
