#!/bin/sh

echo $(date)
set -xe

if [ $# -ne 1 ]; then
   if [ -z "${JENKINS_MASTER}" ] ; then
     echo "Please set JENKINS_MASTER"
     exit 1
   fi
else
  JENKINS_MASTER=$1
fi


# The trailing slash is significant here
SRC=/root/.m2/repository/
DST=jenkins@${JENKINS_MASTER}:/var/lib/jenkins/m2/repository

# Make the rsync call
rsync --archive --stats $SRC $DST

set +x
echo $(date)
