#!/bin/bash
# /etc/init.d/jenkins
# debian-compatible jenkins startup script.
# Jeff Caddel <jcaddel@kuali.org>
#
### BEGIN INIT INFO
# Provides:          jenkins
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start jenkins at boot time
# Description:       Controls the jenkins continuous integration engine.
### END INIT INFO

case "$1" in
  start)
    echo "Starting Jenkins - $(date)"
    ;;
  stop)
    echo "Stopping Jenkins - $(date)"
    ;;
  restart)
    echo "Restarting Jenkins - $(date)"
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
    exit 3
    ;;
esac

exit 0

















