/* Generated By:JavaCC: Do not edit this line. FMParserConstants.java */
package freemarker.core;

interface FMParserConstants {

  int EOF = 0;
  int BLANK = 1;
  int START_TAG = 2;
  int END_TAG = 3;
  int CLOSE_TAG1 = 4;
  int CLOSE_TAG2 = 5;
  int ATTEMPT = 6;
  int RECOVER = 7;
  int IF = 8;
  int ELSE_IF = 9;
  int LIST = 10;
  int FOREACH = 11;
  int SWITCH = 12;
  int CASE = 13;
  int ASSIGN = 14;
  int GLOBALASSIGN = 15;
  int LOCALASSIGN = 16;
  int _INCLUDE = 17;
  int IMPORT = 18;
  int FUNCTION = 19;
  int MACRO = 20;
  int TRANSFORM = 21;
  int VISIT = 22;
  int STOP = 23;
  int RETURN = 24;
  int CALL = 25;
  int DYNCALL = 26;
  int SETTING = 27;
  int COMPRESS = 28;
  int COMMENT = 29;
  int TERSE_COMMENT = 30;
  int NOPARSE = 31;
  int END_IF = 32;
  int END_LIST = 33;
  int END_RECOVER = 34;
  int END_ATTEMPT = 35;
  int END_FOREACH = 36;
  int END_LOCAL = 37;
  int END_GLOBAL = 38;
  int END_ASSIGN = 39;
  int END_FUNCTION = 40;
  int END_MACRO = 41;
  int END_COMPRESS = 42;
  int END_TRANSFORM = 43;
  int END_SWITCH = 44;
  int ELSE = 45;
  int BREAK = 46;
  int SIMPLE_RETURN = 47;
  int HALT = 48;
  int FLUSH = 49;
  int TRIM = 50;
  int LTRIM = 51;
  int RTRIM = 52;
  int NOTRIM = 53;
  int DEFAUL = 54;
  int SIMPLE_NESTED = 55;
  int NESTED = 56;
  int SIMPLE_RECURSE = 57;
  int RECURSE = 58;
  int FALLBACK = 59;
  int ESCAPE = 60;
  int END_ESCAPE = 61;
  int NOESCAPE = 62;
  int END_NOESCAPE = 63;
  int UNIFIED_CALL = 64;
  int UNIFIED_CALL_END = 65;
  int FTL_HEADER = 66;
  int TRIVIAL_FTL_HEADER = 67;
  int UNKNOWN_DIRECTIVE = 68;
  int WHITESPACE = 69;
  int PRINTABLE_CHARS = 70;
  int FALSE_ALERT = 71;
  int OUTPUT_ESCAPE = 72;
  int NUMERICAL_ESCAPE = 73;
  int ESCAPED_CHAR = 81;
  int STRING_LITERAL = 82;
  int RAW_STRING = 83;
  int FALSE = 84;
  int TRUE = 85;
  int INTEGER = 86;
  int DECIMAL = 87;
  int DOT = 88;
  int DOT_DOT = 89;
  int BUILT_IN = 90;
  int EXISTS = 91;
  int EQUALS = 92;
  int DOUBLE_EQUALS = 93;
  int NOT_EQUALS = 94;
  int LESS_THAN = 95;
  int LESS_THAN_EQUALS = 96;
  int ESCAPED_GT = 97;
  int ESCAPED_GTE = 98;
  int PLUS = 99;
  int MINUS = 100;
  int TIMES = 101;
  int DOUBLE_STAR = 102;
  int ELLIPSIS = 103;
  int DIVIDE = 104;
  int PERCENT = 105;
  int AND = 106;
  int OR = 107;
  int EXCLAM = 108;
  int COMMA = 109;
  int SEMICOLON = 110;
  int COLON = 111;
  int OPEN_BRACKET = 112;
  int CLOSE_BRACKET = 113;
  int OPEN_PAREN = 114;
  int CLOSE_PAREN = 115;
  int OPEN_BRACE = 116;
  int CLOSE_BRACE = 117;
  int IN = 118;
  int AS = 119;
  int USING = 120;
  int ID = 121;
  int LETTER = 122;
  int DIGIT = 123;
  int DIRECTIVE_END = 124;
  int EMPTY_DIRECTIVE_END = 125;
  int NATURAL_GT = 126;
  int NATURAL_GTE = 127;
  int TERMINATING_WHITESPACE = 128;
  int TERMINATING_EXCLAM = 129;
  int TERSE_COMMENT_END = 130;
  int MAYBE_END = 131;
  int KEEP_GOING = 132;
  int LONE_LESS_THAN_OR_DASH = 133;

  int DEFAULT = 0;
  int NODIRECTIVE = 1;
  int FM_EXPRESSION = 2;
  int IN_PAREN = 3;
  int NAMED_PARAMETER_EXPRESSION = 4;
  int EXPRESSION_COMMENT = 5;
  int NO_SPACE_EXPRESSION = 6;
  int NO_PARSE = 7;

  String[] tokenImage = {
    "<EOF>",
    "<BLANK>",
    "<START_TAG>",
    "<END_TAG>",
    "<CLOSE_TAG1>",
    "<CLOSE_TAG2>",
    "<ATTEMPT>",
    "<RECOVER>",
    "<IF>",
    "<ELSE_IF>",
    "<LIST>",
    "<FOREACH>",
    "<SWITCH>",
    "<CASE>",
    "<ASSIGN>",
    "<GLOBALASSIGN>",
    "<LOCALASSIGN>",
    "<_INCLUDE>",
    "<IMPORT>",
    "<FUNCTION>",
    "<MACRO>",
    "<TRANSFORM>",
    "<VISIT>",
    "<STOP>",
    "<RETURN>",
    "<CALL>",
    "<DYNCALL>",
    "<SETTING>",
    "<COMPRESS>",
    "<COMMENT>",
    "<TERSE_COMMENT>",
    "<NOPARSE>",
    "<END_IF>",
    "<END_LIST>",
    "<END_RECOVER>",
    "<END_ATTEMPT>",
    "<END_FOREACH>",
    "<END_LOCAL>",
    "<END_GLOBAL>",
    "<END_ASSIGN>",
    "<END_FUNCTION>",
    "<END_MACRO>",
    "<END_COMPRESS>",
    "<END_TRANSFORM>",
    "<END_SWITCH>",
    "<ELSE>",
    "<BREAK>",
    "<SIMPLE_RETURN>",
    "<HALT>",
    "<FLUSH>",
    "<TRIM>",
    "<LTRIM>",
    "<RTRIM>",
    "<NOTRIM>",
    "<DEFAUL>",
    "<SIMPLE_NESTED>",
    "<NESTED>",
    "<SIMPLE_RECURSE>",
    "<RECURSE>",
    "<FALLBACK>",
    "<ESCAPE>",
    "<END_ESCAPE>",
    "<NOESCAPE>",
    "<END_NOESCAPE>",
    "<UNIFIED_CALL>",
    "<UNIFIED_CALL_END>",
    "<FTL_HEADER>",
    "<TRIVIAL_FTL_HEADER>",
    "<UNKNOWN_DIRECTIVE>",
    "<WHITESPACE>",
    "<PRINTABLE_CHARS>",
    "<FALSE_ALERT>",
    "\"${\"",
    "\"#{\"",
    "<token of kind 74>",
    "<token of kind 75>",
    "<token of kind 76>",
    "\">\"",
    "\"]\"",
    "\"-\"",
    "<token of kind 80>",
    "<ESCAPED_CHAR>",
    "<STRING_LITERAL>",
    "<RAW_STRING>",
    "\"false\"",
    "\"true\"",
    "<INTEGER>",
    "<DECIMAL>",
    "\".\"",
    "\"..\"",
    "\"?\"",
    "\"??\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "<LESS_THAN>",
    "<LESS_THAN_EQUALS>",
    "<ESCAPED_GT>",
    "<ESCAPED_GTE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"**\"",
    "\"...\"",
    "\"/\"",
    "\"%\"",
    "<AND>",
    "<OR>",
    "\"!\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"in\"",
    "\"as\"",
    "\"using\"",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\">\"",
    "<EMPTY_DIRECTIVE_END>",
    "\">\"",
    "\">=\"",
    "<TERMINATING_WHITESPACE>",
    "<TERMINATING_EXCLAM>",
    "<TERSE_COMMENT_END>",
    "<MAYBE_END>",
    "<KEEP_GOING>",
    "<LONE_LESS_THAN_OR_DASH>",
  };

}
