#!/bin/sh -x

USER=j2eemgr; typeset -rx USER
EXEC_TIME=`date +%Y%m%d.%H.%M.%S`; typeset -rx EXEC_TIME
BASE_DIRECTORY=/home/$USER/kuali/cvs-svn-staging/; typeset -rx BASE_DIRECTORY
APPLICATION_DIRECTORY=$BASE_DIRECTORY/$APPLICATION; typeset -rx APPLICATION_DIRECTORY
LOGS_DIRECTORY=$APPLICATION_DIRECTORY/logs; typeset -rx LOGS_DIRECTORY
SCRIPT_NAME=`basename $0`; typeset -rx SCRIPT_NAME
SCRIPT_LOG=$LOGS_DIRECTORY/$SCRIPT_NAME+$EXEC_TIME.$$; typeset -rx SCRIPT_LOG

{
    DATABASE_CVS_MODULE=kul-cfg-dbs; typeset -rx DATABASE_CVS_MODULE
    DEPLOY_BASE_DIRECTORY=/opt/ears; typeset -rx DEPLOY_BASE_DIRECTORY
    DEPLOY_COMMAND=/usr/local/bin/appdeploy; typeset -rx DEPLOY_COMMAND
    DEPLOY_TAG_FILE=cvs-tag.properties; typeset -rx DEPLOY_TAG_FILE
	DEPLOY_PROPERTIES_FILE=build.properties; typeset -rx DEPLOY_BUILD_FILE
    WORK_PURGE_COMMAND=/usr/local/bin/j2ee_deploy_work
    ANT_COMMAND=/usr/local/ant/bin/ant
    ANT_PROPERTIES_TEMPLATE=$BASE_DIRECTORY/build.properties
    ANT_PROPERTIES_FILE=$APPLICATION_DIRECTORY/build.properties
    ANT_BUILD_FILE=$BASE_DIRECTORY/build.xml
    export JAVA_HOME=/usr/local/java
    BUILD_NUMBER_FILE=$APPLICATION_DIRECTORY/build-number.txt; typeset -rx BUILD_NUMBER_FILE
	SRCCTRL_URL=https://test.kuali.org/svn; typeset -rx SRCCTRL_URL

    cd $BASE_DIRECTORY
} >> $SCRIPT_LOG 2>&1