#!/bin/sh -x

#set -x
SEND_MAIL=true; typeset -rx SEND_MAIL
#SEND_MAIL=false; typeset -rx SEND_MAIL

USER=j2eemgr; typeset -rx USER
EXEC_TIME=`date +%Y%m%d.%H.%M.%S`; typeset -rx EXEC_TIME
BASE_DIRECTORY=/home/$USER/kuali; typeset -rx BASE_DIRECTORY
WORKING_DIRECTORY=$BASE_DIRECTORY/$APPLICATION; typeset -rx WORKING_DIRECTORY
LOGS_DIRECTORY=$WORKING_DIRECTORY/logs; typeset -rx LOGS_DIRECTORY
SCRIPT_NAME=`basename $0`; typeset -rx SCRIPT_NAME
SCRIPT_LOG=$LOGS_DIRECTORY/$SCRIPT_NAME+$EXEC_TIME.$$; typeset -rx SCRIPT_LOG

{
    DATABASE_CVS_MODULE=kul-cfg-dbs; typeset -rx DATABASE_CVS_MODULE
    DEPLOY_BASE_DIRECTORY=/opt/ears; typeset -rx DEPLOY_BASE_DIRECTORY
    DEPLOY_COMMAND=/usr/local/bin/appdeploy; typeset -rx DEPLOY_COMMAND
    DEPLOY_TAG_FILE=cvs-tag.properties; typeset -rx DEPLOY_TAG_FILE
	DEPLOY_BUILD_FILE=build.properties; typeset -rx DEPLOY_BUILD_FILE
    ATTACHMENTS_PURGE_COMMAND=/usr/local/bin/j2ee_purge_kuali_attachments
    ANT_COMMAND=/usr/local/ant/bin/ant
    ANT_FILE=$BASE_DIRECTORY/build.xml
    ANT_ARGS_PREFIX="-Dapplication="$DATABASE_APPLICATION_CODE" -Dworking.directory="$WORKING_DIRECTORY
    export JAVA_HOME=/usr/local/java
    BUILD_NUMBER_FILE=$WORKING_DIRECTORY/build_number.txt; typeset -rx BUILD_NUMBER_FILE

    cd $WORKING_DIRECTORY
} >> $SCRIPT_LOG 2>&1