INSERT INTO FOO (CMPNT_SET_ID, LAST_UPDT_TS, CHKSM, VER_NBR) VALUES ('1',SYSDATE(),'abc',17)
/

INSERT INTO FOO (CMPNT_SET_ID, LAST_UPDT_TS, CHKSM, VER_NBR) VALUES ('2',SYSDATE(),'def',27)
/

INSERT INTO FOO (CMPNT_SET_ID, LAST_UPDT_TS, CHKSM, VER_NBR) VALUES ('3',SYSDATE(),'ghi',37)
/
