#!/bin/bash

function check_args {
  check_not_blank GROUP_ID $GROUP_ID
  check_not_blank ARTIFACT_ID $ARTIFACT_ID
  check_not_blank VERSION $VERSION
  check_not_blank TYPE $TYPE
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h] [-q] [--help] [--quiet] [--classifier=linux-x64] [--type=zip] group_id artifact_id version" 1>&2; exit 1; }

QUIET=false
MAVEN_CLASSIFIER=""
MAVEN_TYPE=jar

ARGS=$(getopt --options hqc:t: --longoptions "help,quiet,classifier:,type:," --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -q|--quiet)
      QUIET="true";
      shift;
      ;;
    --classifier)
      shift;
      CLASSIFIER="$1";
      shift;
      ;;
    --type)
      shift;
      TYPE="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done

MAVEN_GROUP_ID=$1
MAVEN_ARTIFACT_ID=$2
MAVEN_VERSION=$3

check_args
