#!/bin/bash

function check_args {
  check_not_blank GROUP_ID $GROUP_ID
  check_not_blank ARTIFACT_ID $ARTIFACT_ID
  check_not_blank VERSION $VERSION
  check_not_blank TYPE $TYPE
  check_not_blank URL $URL
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h] [-q] [--help] [--quiet] [--classifier=linux-x64] [--type=zip] [--username=developer] [--password=password] group_id artifact_id version url" 1>&2; exit 1; }

QUIET=false
CLASSIFIER=""
TYPE=jar
USERNAME=""
PASSWORD=""

ARGS=$(getopt --options hqc:t:u:p: --longoptions "help,quiet,classifier:,type:,username:,password:" --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -q|--quiet)
      QUIET=true;
      shift;
      ;;
    -c|--classifier)
      shift;
      CLASSIFIER="$1";
      shift;
      ;;
    -p|--password)
      shift;
      PASSWORD="$1";
      shift;
      ;;
    -u|--username)
      shift;
      USERNAME="$1";
      shift;
      ;;
    -t|--type)
      shift;
      TYPE="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done

GROUP_ID=$1
ARTIFACT_ID=$2
VERSION=$3
URL=$4

check_args
