#!/bin/bash

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

execute_quietly "apt-get install mdadm -y --no-install-recommends"
if [ -d "/mnt" ]; then
  execute_quietly "umount /mnt"
  execute_quietly "yes | mdadm --create --verbose /dev/md/ssd --level=stripe --raid-devices=2 /dev/xvdb /dev/xvdc" 
  execute_quietly "mkfs.ext3 /dev/md/ssd" 
  execute_quietly "mkdir -p /ssd"
  execute_quietly "mount /dev/md/ssd /ssd"
  execute_quietly "rm /mnt"
fi
