#!/bin/bash

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

OLD_SSD_MOUNT="/mnt"
NEW_SSD_MOUNT="/ssd"

execute_quietly "apt-get install mdadm -y --no-install-recommends"
if mountpoint -q $OLD_SSD_MOUNT then;
  umount $OLD_SSD_MOUNT
fi

#execute_quietly "yes | mdadm --create --verbose /dev/md/ssd --level=stripe --raid-devices=2 /dev/xvdb /dev/xvdc" 
#execute_quietly "mkfs.ext3 /dev/md/ssd" 
#execute_quietly "mkdir -p $NEW_SSD_MOUNT"
#execute_quietly "mount /dev/md/ssd $NEW_SSD_MOUNT"
#execute_quietly "rm $OLD_SSD_MOUNT"
