#!/bin/bash

function check_args {
  check_not_blank JDK $JDK
  check_not_blank UPDATE $UPDATE
  check_not_blank BUILD $BUILD
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h --help] [-q --quiet] [-c --classifier=linux-x64] [-t --type=tar.gz] [--cookies=\$HOME/cookies.txt] jdk7/jdk8 u51/u0 b13/b132" 1>&2; exit 1; }

QUIET=false
CLASSIFIER=linux-x64
TYPE=tar.gz
COOKIES=$HOME/cookies.txt

ARGS=$(getopt --options hqc:t:d: --longoptions "help,quiet,classifier:,type:,cookies:,downloads:" --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -q|--quiet)
      QUIET=true;
      shift;
      ;;
    -c|--classifier)
      shift;
      CLASSIFIER="$1";
      shift;
      ;;
    -t|--type)
      shift;
      TYPE="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done


JDK=$1
UPDATE=$2
BUILD=$3

check_args

JDK_LEVEL=${JDK:3:1}
GROUP_ID=com.oracle
ARTIFACT_ID=$JDK

# The very first JDK8 just came out and so there is no update version
# eg it's just jdk-8-linux-x64.tar.gz instead of jdk-8u5-linux-x64.tar.gz
# http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz
if [ "$UPDATE" == "u0" ]; then
  FILENAME=jdk-$JDK_LEVEL-$CLASSIFIER.$TYPE
else
  FILENAME=jdk-$JDK_LEVEL-$CLASSIFIER.$TYPE
fi
URL=http://download.oracle.com/otn-pub/java/jdk/$JDK_LEVEL$UPDATE-$BUILD/$FILENAME

CLASSIFIER=$CLASSIFIER-orginal

FULLPATH=$($MY_DIR/m2path $GROUP_ID $ARTIFACT_ID $VERSION --classifier=$CLASSIFIER --type=$TYPE)

download -c $COOKIES $URL $FULLPATH
 