#!/bin/bash
#
# Copyright 2004-2014 The Kuali Foundation
#
# Licensed under the Educational Community License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.opensource.org/licenses/ecl2.php
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function install_jdk {

  # Extract the jdk level from the JDK variable
  LEVEL=${JDK:3:1}
  
  GROUP_ID=com.oracle
  ARTIFACT_ID=$JDK
  CLASSIFIER=linux-x64
  VERSION=1.$LEVEL.0-$UPDATE
  TYPE=tar.gz

  ACCESS_KEY=AKIAJFD5IM7IPVVUEBNA
  SECRET_KEY=jA0ECQMCcSOVTI3J0Ym+0l0B3rTDQ9MBRtjvjvT6LvPxk2Aqqx/bqYPNzU42uL+EBSh//otXUlFhqnnizUm1iald6rntwAnbUxLlza463B7wu8s+J3Y00GtCm3A/bbuPCfuRnOGRDsg+t8Gfi7E=
  SECRET_KEY=$(decrypt $SECRET_KEY $GPG_PASSPHRASE)
  BUCKET=maven.kuali.org
  PREFIX=private

  # Download and cache the jdk
  $MY_DIR/m2s3get $QUIET_FLAG $ACCESS_KEY $SECRET_KEY $BUCKET $GROUP_ID $ARTIFACT_ID $VERSION --prefix=$PREFIX --classifier=$CLASSIFIER --type=$TYPE
  
  exit 1
  
  JDK_DIR=$ARTIFACT_ID-$VERSION
  BASEDIR=/usr/java
  mkdir -p $BASEDIR

  # Make sure the JDK and the symbolic link are both gone
  TARGET=$BASEDIR/$JDK_DIR
  LINK=$BASEDIR/$ARTIFACT_ID
  echo "purge     -> $JDK"
  rm -rf $LINK $TARGET

  # Unpack the JDK into /usr/java
  echo "install   -> $LINK - [$TARGET]"
  M2_LOCAL_PATH=$($MY_DIR/m2path $GROUP_ID $ARTIFACT_ID $VERSION --classifier="$CLASSIFIER" --type="$TYPE")
  execute_quietly "unzip -o $M2_LOCAL_PATH -d $BASEDIR"

  # Create the symbolic link  eg: /usr/java/jdk7 -> /usr/java/jdk7-1.7.0-u51
  execute_quietly "ln -s $TARGET $LINK"
  
}

function check_args {

  check_not_blank JDK $JDK
  check_not_blank UPDATE $UPDATE
  check_not_blank GPG_PASSPHRASE $GPG_PASSPHRASE
  check_jdk
    
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h] [-q] jdk6/jdk7/jdk8 u45/u51/u0 password" 1>&2; exit 1; }

QUIET=false
while getopts hq flag; do
  case $flag in
    h)
      usage;
      ;;
    q)
      QUIET="true";
      ;;
    ?)
      usage;
      exit;
      ;;
  esac
done

shift $(( OPTIND - 1 ));

JDK=$1
UPDATE=$2
GPG_PASSPHRASE=$3

check_args

QUIET_FLAG=""
if [ "$QUIET" == "true" ]; then
  QUIET_FLAG="-q"
fi

install_jdk
