#!/bin/bash

function check_args {
  check_not_blank UPDATE $UPDATE
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h --help] [-q --quiet] [-c --classifier=linux-x64] u45" 1>&2; exit 1; }

QUIET=false
CLASSIFIER=linux-x64

ARGS=$(getopt --options hqc:t: --longoptions "help,quiet,classifier:" --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -q|--quiet)
      QUIET=true;
      shift;
      ;;
    -c|--classifier)
      shift;
      CLASSIFIER="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done

UPDATE=$1

check_args

JDK=jdk6

JDK_LEVEL=${JDK:3:1}
GROUP_ID=com.oracle
ARTIFACT_ID=$JDK
VERSION=1.$JDK_LEVEL.0-$UPDATE
TYPE=bin

OLD_CLASSIFIER=$CLASSIFIER-original
NEW_CLASSIFIER=$CLASSIFIER

OLD_M2_LOCAL_PATH=$($MY_DIR/m2path $GROUP_ID $ARTIFACT_ID $VERSION --classifier=$OLD_CLASSIFIER --type=$TYPE)

OLD_M2_FILENAME=$($MY_DIR/m2filename $ARTIFACT_ID $VERSION --classifier=$OLD_CLASSIFIER --type=$TYPE)
NEW_M2_FILENAME=$($MY_DIR/m2filename $ARTIFACT_ID $VERSION --classifier=$NEW_CLASSIFIER --type=$TYPE)

if [ "$UPDATE" == "u0" ]; then
  OLD_UNPACK_DIR=jdk1.$JDK_LEVEL.0
else
  OLD_UNPACK_DIR=jdk1.$JDK_LEVEL.0_${UPDATE:1}
fi
NEW_UNPACK_DIR=$JDK-$VERSION

check_exists $OLD_M2_LOCAL_PATH

DIR=$(dirname $OLD_M2_LOCAL_PATH)

set -x

# change into the correct M2 repo dir
cd $DIR

# purge any old dirs that may be laying around
rm -rf $OLD_UNPACK_DIR $NEW_UNPACK_DIR

# make sure the .bin file is executable
chmod 755 $OLD_M2_FILENAME
