#!/bin/bash

function check_args {
  check_not_blank JDK $JDK
  check_not_blank UPDATE $UPDATE
  check_not_blank BUILD $BUILD
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h --help] [-q --quiet] [-c --classifier=linux-x64] [-t --type=tar.gz] jdk7/jdk8 u51/u0" 1>&2; exit 1; }

QUIET=false
CLASSIFIER=linux-x64
TYPE=tar.gz

ARGS=$(getopt --options hqc:t: --longoptions "help,quiet,classifier:,type:" --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -q|--quiet)
      QUIET=true;
      shift;
      ;;
    -c|--classifier)
      shift;
      CLASSIFIER="$1";
      shift;
      ;;
    -t|--type)
      shift;
      TYPE="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done


JDK=$1
UPDATE=$2
BUILD=$3

check_args

JDK_LEVEL=${JDK:3:1}
GROUP_ID=com.oracle
ARTIFACT_ID=$JDK
VERSION=1.$JDK_LEVEL.0-$UPDATE
CLASSIFIER=$CLASSIFIER-original

M2_LOCAL_PATH=$($MY_DIR/m2path $GROUP_ID $ARTIFACT_ID $VERSION --classifier=$CLASSIFIER --type=$TYPE)

check_exists $M2_LOCAL_PATH
 