#!/bin/bash

function check_args {
  check_not_blank JDK $JDK
  check_not_blank UPDATE $UPDATE
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h --help] [-q --quiet] [-c --classifier=linux-x64] [-t --type=tar.gz] jdk7/jdk8 u51/u0" 1>&2; exit 1; }

QUIET=false
CLASSIFIER=linux-x64
TYPE=tar.gz

ARGS=$(getopt --options hqc:t: --longoptions "help,quiet,classifier:,type:" --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -q|--quiet)
      QUIET=true;
      shift;
      ;;
    -c|--classifier)
      shift;
      CLASSIFIER="$1";
      shift;
      ;;
    -t|--type)
      shift;
      TYPE="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done


JDK=$1
UPDATE=$2

check_args

JDK_LEVEL=${JDK:3:1}
GROUP_ID=com.oracle
ARTIFACT_ID=$JDK
VERSION=1.$JDK_LEVEL.0-$UPDATE

OLD_CLASSIFIER=$CLASSIFIER-original
NEW_CLASSIFIER=$CLASSIFIER

OLD_M2_LOCAL_PATH=$($MY_DIR/m2path $GROUP_ID $ARTIFACT_ID $VERSION --classifier=$OLD_CLASSIFIER --type=$TYPE)

OLD_M2_FILENAME=$($MY_DIR/m2filename $ARTIFACT_ID $VERSION --classifier=$OLD_CLASSIFIER --type=$TYPE)
NEW_M2_FILENAME=$($MY_DIR/m2filename $ARTIFACT_ID $VERSION --classifier=$NEW_CLASSIFIER --type=$TYPE)

if [ "$UPDATE" == "u0" ]; then
  OLD_UNPACK_DIR=jdk1.$JDK_LEVEL.0
else
  OLD_UNPACK_DIR=jdk1.$JDK_LEVEL.0_${UPDATE:1}
fi
NEW_UNPACK_DIR=$JDK-$VERSION

check_exists $OLD_M2_LOCAL_PATH

DIR=$(dirname $OLD_M2_LOCAL_PATH)

set -x

# change into the correct M2 repo dir
cd $DIR

# purge any old dirs that may be laying around
rm -rf $OLD_UNPACK_DIR $NEW_UNPACK_DIR

# extract the original .tar.gz from Oracle
tar --extract --file $OLD_M2_FILENAME

# change 1.7.0_51 -> 1.7.0-u51
mv $OLD_UNPACK_DIR $NEW_UNPACK_DIR

# don't need any of the zipped up source code
rm -f $NEW_UNPACK_DIR/*src.zip

# Copy tools.jar into the jar dir (AppDynamics is unable to provide detailed heap statistics without this)
cp $NEW_UNPACK_DIR/lib/tools.jar $NEW_UNPACK_DIR/jre/lib/ext/tools.jar

# Create a tar.gz from the 1.7.0-u51 directory
tar --gzip --create --file $NEW_M2_FILENAME $NEW_UNPACK_DIR

# Remove the 1.7.0-u51 directory
rm -rf $NEW_UNPACK_DIR
