#!/bin/bash

function check_args {
  check_not_blank COOKIES $COOKIES
  check_not_blank UPDATE $UPDATE
  check_not_blank BUILD $BUILD
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h --help] [-q --quiet] [-c --classifier=linux-x64] [--cookies=\$HOME/Downloads/cookies.txt] [-t --type=tar.gz] jdk7/jdk8 u51/u0 b13/b132" 1>&2; exit 1; }

QUIET=false
CLASSIFIER=linux-x64
TYPE=tar.gz
COOKIES=$HOME/Downloads/cookies.txt

ARGS=$(getopt --options hqc:t: --longoptions "help,quiet,cookies:,classifier:,type:" --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -q|--quiet)
      QUIET=true;
      shift;
      ;;
    -c|--classifier)
      shift;
      CLASSIFIER="$1";
      shift;
      ;;
    -t|--type)
      shift;
      TYPE="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done

JDK=$1
UPDATE=$2
BUILD=$3

check_args

# http://download.oracle.com/otn-pub/java/jdk/8-b132/jdk-8-linux-x64.tar.gz
# http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz

DOWNLOADS=$HOME/Downloads/jdks
URL=http://download.oracle.com/otn-pub/java/jdk/7$UPDATE-$BUILD/jdk-7$BUILD-$CLASSIFIER.$TYPE
