#!/bin/bash

function check_args {
  check_not_blank JDK $JDK
  check_not_blank UPDATE $UPDATE
  check_not_blank GPG_PASSPHRASE $GPG_PASSPHRASE
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h --help] [-q --quiet] [-c --classifier=linux-x64] [-t --type=tar.gz] [-b --bucket=maven.kuali.org] [-p --prefix=private] [-a --acl=authenticated-read] jdk7/jdk8 u51/u0 password" 1>&2; exit 1; }

QUIET=false
CLASSIFIER=linux-x64
TYPE=tar.gz
BUCKET=maven.kuali.org
PREFIX=private
ACL=authenticated-read

ARGS=$(getopt --options hqc:t:b:p:a: --longoptions "help,quiet,classifier:,type:,bucket:,prefix:,acl:" --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -q|--quiet)
      QUIET=true;
      shift;
      ;;
    -c|--classifier)
      shift;
      CLASSIFIER="$1";
      shift;
      ;;
    -t|--type)
      shift;
      TYPE="$1";
      shift;
      ;;
    -b|--bucket)
      shift;
      BUCKET="$1";
      shift;
      ;;
    -p|--prefix)
      shift;
      PREFIX="$1";
      shift;
      ;;
    -a|--acl)
      shift;
      ACL="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done


JDK=$1
UPDATE=$2
GPG_PASSPHRASE=$3

check_args

JDK_LEVEL=${JDK:3:1}
GROUP_ID=com.oracle
ARTIFACT_ID=$JDK
VERSION=1.$JDK_LEVEL.0-$UPDATE

M2_LOCAL_PATH=$($MY_DIR/m2path $GROUP_ID $ARTIFACT_ID $VERSION --classifier=$CLASSIFIER --type=$TYPE)

check_exists $M2_LOCAL_PATH

ACCESS_KEY=AKIAJFD5IM7IPVVUEBNA
SECRET_KEY=jA0ECQMCcSOVTI3J0Ym+0l0B3rTDQ9MBRtjvjvT6LvPxk2Aqqx/bqYPNzU42uL+EBSh//otXUlFhqnnizUm1iald6rntwAnbUxLlza463B7wu8s+J3Y00GtCm3A/bbuPCfuRnOGRDsg+t8Gfi7E=
SECRET_KEY=$(decrypt $SECRET_KEY $GPG_PASSPHRASE)

echo "upload    -> $BUCKET/$PREFIX $GROUP_ID:$ARTIFACT_ID:$VERSION:$CLASSIFIER"
$MY_DIR/m2s3put --prefix=$PREFIX --type=$TYPE --acl=$ACL --classifier=$CLASSIFIER $M2_LOCAL_PATH $ACCESS_KEY $SECRET_KEY $BUCKET $GROUP_ID $ARTIFACT_ID $VERSION
