#!/bin/bash

function check_args {
  check_not_blank REPO $REPO
  check_not_blank GROUP_ID $GROUP_ID
  check_not_blank ARTIFACT_ID $ARTIFACT_ID
  check_not_blank VERSION $VERSION
  check_not_blank CLASSIFIER $CLASSIFIER
  check_not_blank TYPE $TYPE
  check_not_blank URL $URL
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h --help] [-q --quiet] [-c --classifier=linux-x64] [-t --type=zip] [-u --username=developer] [-p --password=password] [-r --repo=\$HOME/.m2/repository] group_id artifact_id version url" 1>&2; exit 1; }

QUIET=false
REPO=$HOME/.m2/repository
CLASSIFIER=""
TYPE=jar
USERNAME=""
PASSWORD=""

ARGS=$(getopt --options hqc:t:u:p: --longoptions "help,quiet,classifier:,type:,username:,password:" --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -q|--quiet)
      QUIET=true;
      shift;
      ;;
    -r|--repo)
      shift;
      REPO="$1";
      shift;
      ;;
    -c|--classifier)
      shift;
      CLASSIFIER="$1";
      shift;
      ;;
    -p|--password)
      shift;
      PASSWORD="$1";
      shift;
      ;;
    -u|--username)
      shift;
      USERNAME="$1";
      shift;
      ;;
    -t|--type)
      shift;
      TYPE="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done

GROUP_ID=$1
ARTIFACT_ID=$2
VERSION=$3
URL=$4

check_args

M2_REPO_LOCAL=$HOME/.m2/repository
DEPENDENCY_FILENAME=$(get_m2_repo_filename $M2_REPO_LOCAL $GROUP_ID $ARTIFACT_ID $VERSION $CLASSIFIER $TYPE)
if [ ! -f $DEPENDENCY_FILENAME ]; then
  echo "download  -> $URL"
  echo "to        -> $DEPENDENCY_FILENAME"
  download_url $URL $DEPENDENCY_FILENAME $USERNAME $PASSWORD
else 
  echo "skip      -> $URL"
  echo "because   -> $DEPENDENCY_FILENAME already exists"
fi
