#!/bin/bash

function check_args {
  check_not_blank ARTIFACT_ID $ARTIFACT_ID
  check_not_blank VERSION $VERSION
  check_not_blank CLASSIFIER $CLASSIFIER
  check_not_blank TYPE $TYPE
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h] [--help] [--classifier=linux-x64] [--type=zip] artifact_id version" 1>&2; exit 1; }

CLASSIFIER=""
TYPE=jar
USERNAME=""
PASSWORD=""

ARGS=$(getopt --options hc:t: --longoptions "help,classifier:,type:" --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -c|--classifier)
      shift;
      CLASSIFIER="$1";
      shift;
      ;;
    -p|--password)
      shift;
      PASSWORD="$1";
      shift;
      ;;
    -u|--username)
      shift;
      USERNAME="$1";
      shift;
      ;;
    -t|--type)
      shift;
      TYPE="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done

GROUP_ID=$1
ARTIFACT_ID=$2
VERSION=$3

if [ "$CLASSIFIER" == "" ]; then
  CLASSIFIER="none"
fi

check_args

if [ "$CLASSIFIER" == "none" ]; then
  echo "$ARTIFACT_ID-$VERSION.$TYPE"	  
else
  echo "$ARTIFACT_ID-$VERSION-$CLASSIFIER.$TYPE"	  
fi
