#!/bin/bash

function check_args {
  check_not_blank REPO $REPO
  check_not_blank GROUP_ID $GROUP_ID
  check_not_blank ARTIFACT_ID $ARTIFACT_ID
  check_not_blank VERSION $VERSION
  check_not_blank TYPE $TYPE
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME [-h --help] [-c --classifier=linux-x64] [-t --type=zip] [-r --repo=HOME/.m2/repository] group_id artifact_id version" 1>&2; exit 1; }

CLASSIFIER=""
TYPE=jar
REPO="$HOME/.m2/repository"

ARGS=$(getopt --options hc:t:r: --longoptions "help,classifier:,type:,repo:" --name "$ME" -- "$@");
if [ $? -ne 0 ]; then usage; fi
eval set -- "$ARGS";
while true; do
  case "$1" in
    -h|--help)
      usage;
      shift;
      ;;
    -c|--classifier)
      shift;
      CLASSIFIER="$1";
      shift;
      ;;
    -r|--repo)
      shift;
      REPO="$1";
      shift;
      ;;
    -t|--type)
      shift;
      TYPE="$1";
      shift;
      ;;
    --)
      shift;
      break;
      ;;
  esac
done

GROUP_ID=$1
ARTIFACT_ID=$2
VERSION=$3

check_args

# Replace any dots with a forward slash in the group id
GROUP_ID=$(get_path $GROUP_ID)

M2_FILENAME=$($MY_DIR/m2filename $ARTIFACT_ID $VERSION --classifier="$CLASSIFIER" --type="$TYPE")
echo "$REPO/$GROUP_ID/$ARTIFACT_ID/$VERSION/$M2_FILENAME"

