#!/bin/bash

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

umount -l /dev/md127
mdadm --stop /dev/md127
mdadm --zero-superblock /dev/xvdb
mdadm --zero-superblock /dev/xvdc
##mdadm --remove /dev/md127