#!/bin/bash

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

QUIET=$1
if [ "$QUIET" = "-q" ]; then
  QUIET=true
fi

DEVICE="/dev/md127"

echo "remove    -> ssd"
execute_quietly "umount -l $DEVICE"
execute_quietly "mdadm --stop $DEVICE"
execute_quietly "mdadm --zero-superblock /dev/xvdb"
execute_quietly "mdadm --zero-superblock /dev/xvdc"
