#!/bin/bash
#
# Copyright 2004-2014 The Kuali Foundation
#
# Licensed under the Educational Community License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.opensource.org/licenses/ecl2.php
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Set hostname and FQDN
function set_hostname {

  # Mike is insane
  MYIP=$(ifconfig eth0 |grep inet | awk '{ print $2 }' | awk 'BEGIN { FS=":" } { print $2 }')

  ETC_HOSTS="$MYIP $SUBDOMAIN.$DOMAIN $SUBDOMAIN"
  echo "hostname  -> $SUBDOMAIN"
  echo "hosts     -> $ETC_HOSTS"

  echo "$SUBDOMAIN" > /etc/hostname
  hostname $SUBDOMAIN

  echo '127.0.0.1 localhost' > /etc/hosts
  echo $ETC_HOSTS >> /etc/hosts
 
  # Mike's magic line here always appends to /etc/hosts
  # This breaks with the concept of idempotence
  # And also if for some reason we gave the machine a new DNS name I think we'd have issues 
  # eval "sed -i -e '/127.0.0.1/a$ETC_HOSTS' /etc/hosts"
  
}

function check_args {
  check_not_blank SUBDOMAIN $SUBDOMAIN
  check_not_blank DOMAIN $DOMAIN
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/functions.sh

usage() { echo "Usage: $ME subdomain domain" 1>&2; exit 1; }

# module specific variables
SUBDOMAIN=$1
DOMAIN=$2

# Make sure we have what we need
check_args

set_hostname
