--
-- Copyright 2010-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE CA_ACCTG_CTGRY_T
/
INSERT INTO CA_ACCTG_CTGRY_T (ACCTG_CTGRY_CD,OBJ_ID,VER_NBR,ACCTG_CTGRY_DESC,ACCTG_CTGRY_SHRT_NM,FIN_REPORT_SORT_CD,ROW_ACTV_IND)
  VALUES ('AS','2ECB4157BE1060E4E043814FD88160E4',1.0,'ASSETS','ASSETS','01','Y')
/
INSERT INTO CA_ACCTG_CTGRY_T (ACCTG_CTGRY_CD,OBJ_ID,VER_NBR,ACCTG_CTGRY_DESC,ACCTG_CTGRY_SHRT_NM,FIN_REPORT_SORT_CD,ROW_ACTV_IND)
  VALUES ('EX','2ECB4157BE1460E4E043814FD88160E4',1.0,'EXPENSES','EXPENSES','05','Y')
/
INSERT INTO CA_ACCTG_CTGRY_T (ACCTG_CTGRY_CD,OBJ_ID,VER_NBR,ACCTG_CTGRY_DESC,ACCTG_CTGRY_SHRT_NM,FIN_REPORT_SORT_CD,ROW_ACTV_IND)
  VALUES ('FB','2ECB4157BE1260E4E043814FD88160E4',1.0,'FUND BALANCE','FUND BALANCE','03','Y')
/
INSERT INTO CA_ACCTG_CTGRY_T (ACCTG_CTGRY_CD,OBJ_ID,VER_NBR,ACCTG_CTGRY_DESC,ACCTG_CTGRY_SHRT_NM,FIN_REPORT_SORT_CD,ROW_ACTV_IND)
  VALUES ('IN','2ECB4157BE1360E4E043814FD88160E4',1.0,'INCOME','INCOME','04','Y')
/
INSERT INTO CA_ACCTG_CTGRY_T (ACCTG_CTGRY_CD,OBJ_ID,VER_NBR,ACCTG_CTGRY_DESC,ACCTG_CTGRY_SHRT_NM,FIN_REPORT_SORT_CD,ROW_ACTV_IND)
  VALUES ('LI','2ECB4157BE1160E4E043814FD88160E4',1.0,'LIABILITIES','LIABILITIES','02','Y')
/
