--
-- Copyright 2010-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE PUR_AP_CMP_PARM_T
/
INSERT INTO PUR_AP_CMP_PARM_T (CAMPUS_CD,OBJ_ID,VER_NBR,CMP_PUR_DRCTR_NM,CMP_PUR_DRCTR_TTL,PUR_INST_NM,PUR_DEPT_NM,PUR_DEPT_LN1_ADDR,PUR_DEPT_CTY_NM,PUR_DEPT_ST_CD,PUR_DEPT_ZIP_CD,PUR_DEPT_CNTRY_CD,ACTV_IND)
  VALUES ('BL','29A8EDAB-DF3C-D7C1-E370-CD5CAC8D143E',3.0,'SALLY SMITH','UNIVERSITY DIRECTOR OF PURCHASING','UNIVERSITY OF HIGHER ED','PURCHASING DEPARTMENT','ONE MAIN STREET','SOME CITY','AK','99334','US','Y')
/
INSERT INTO PUR_AP_CMP_PARM_T (CAMPUS_CD,OBJ_ID,VER_NBR,CMP_PUR_DRCTR_NM,CMP_PUR_DRCTR_TTL,PUR_INST_NM,PUR_DEPT_NM,PUR_DEPT_LN1_ADDR,PUR_DEPT_CTY_NM,PUR_DEPT_ST_CD,PUR_DEPT_ZIP_CD,PUR_DEPT_CNTRY_CD,ACTV_IND)
  VALUES ('CO','D711CF41-69FA-7CF8-BEE2-9C1D86504CA5',4.0,'JOHN JONES','DIRECTOR OF PURCHASING SERVICES','HIGHER EDUCATION STATE','PURCHASING SERVICES','123 NORTH STREET','POTTERSVILLE','CA','33449','US','Y')
/
INSERT INTO PUR_AP_CMP_PARM_T (CAMPUS_CD,OBJ_ID,VER_NBR,CMP_PUR_DRCTR_NM,CMP_PUR_DRCTR_TTL,PUR_INST_NM,PUR_DEPT_NM,PUR_DEPT_LN1_ADDR,PUR_DEPT_CTY_NM,PUR_DEPT_ST_CD,PUR_DEPT_ZIP_CD,PUR_DEPT_CNTRY_CD,ACTV_IND)
  VALUES ('EA','309C0E9A-8F85-C1B2-C492-32E584B765E5',5.0,'CATHY SMITH','BUSINESS MANAGER','RICHMOND UNIVERSITY','PURCHASE DEPARTMENT','NORTH STREET','RICHMOND','VA','33443','US','Y')
/
INSERT INTO PUR_AP_CMP_PARM_T (CAMPUS_CD,OBJ_ID,VER_NBR,CMP_PUR_DRCTR_NM,CMP_PUR_DRCTR_TTL,PUR_INST_NM,PUR_DEPT_NM,PUR_DEPT_LN1_ADDR,PUR_DEPT_CTY_NM,PUR_DEPT_ST_CD,PUR_DEPT_ZIP_CD,PUR_DEPT_CNTRY_CD,ACTV_IND)
  VALUES ('FW','70FD26C0-FA89-13DB-C51E-8671B7583D48',4.0,'SALLY SMITH','UNIVERSITY DIRECTOR OF PURCHASING','UNIVERSITY OF HIGHER ED','PURCHASING DEPARTMENT','ONE MAIN STREET','SOME CITY','AK','99334','US','Y')
/
INSERT INTO PUR_AP_CMP_PARM_T (CAMPUS_CD,OBJ_ID,VER_NBR,CMP_PUR_DRCTR_NM,CMP_PUR_DRCTR_TTL,PUR_INST_NM,PUR_DEPT_NM,PUR_DEPT_LN1_ADDR,PUR_DEPT_CTY_NM,PUR_DEPT_ST_CD,PUR_DEPT_ZIP_CD,PUR_DEPT_CNTRY_CD,ACTV_IND)
  VALUES ('IN','F8B0BA74-0120-4DF0-C3F6-5B1E2A65197C',5.0,'JOHN JONES','DIRECTOR OF PURCHASING SERVICES','HIGHER EDUCATION STATE','PURCHASING SERVICES','123 NORTH STREET','POTTERSVILLE','CA','33449','US','Y')
/
INSERT INTO PUR_AP_CMP_PARM_T (CAMPUS_CD,OBJ_ID,VER_NBR,CMP_PUR_DRCTR_NM,CMP_PUR_DRCTR_TTL,PUR_INST_NM,PUR_DEPT_NM,PUR_DEPT_LN1_ADDR,PUR_DEPT_CTY_NM,PUR_DEPT_ST_CD,PUR_DEPT_ZIP_CD,PUR_DEPT_CNTRY_CD,ACTV_IND)
  VALUES ('KO','E8FD56F1-E90E-4680-3931-7D858A24911E',6.0,'WILLIAM CARTER','VICE CHANCELLOR','UNIVERSITY OF HIGHER ED','PURCHASING DEPARTMENT','88 NORTH STREET','KOKOMO','UT','77334','US','Y')
/
INSERT INTO PUR_AP_CMP_PARM_T (CAMPUS_CD,OBJ_ID,VER_NBR,CMP_PUR_DRCTR_NM,CMP_PUR_DRCTR_TTL,PUR_INST_NM,PUR_DEPT_NM,PUR_DEPT_LN1_ADDR,PUR_DEPT_CTY_NM,PUR_DEPT_ST_CD,PUR_DEPT_ZIP_CD,PUR_DEPT_CNTRY_CD,ACTV_IND)
  VALUES ('NW','37883DD3-9AC6-0730-14B6-7B22639E8FA4',5.0,'MARY THOMAS','DIRECTOR OF PURCHASING','UNIVERSITY OF HIGHER ED','PURCHASING DEPARTMENT','24 DUPONT LANE','CHARLOTTE','NC','33448','US','Y')
/
INSERT INTO PUR_AP_CMP_PARM_T (CAMPUS_CD,OBJ_ID,VER_NBR,CMP_PUR_DRCTR_NM,CMP_PUR_DRCTR_TTL,PUR_INST_NM,PUR_DEPT_NM,PUR_DEPT_LN1_ADDR,PUR_DEPT_CTY_NM,PUR_DEPT_ST_CD,PUR_DEPT_ZIP_CD,PUR_DEPT_CNTRY_CD,ACTV_IND)
  VALUES ('SB','56DF0A37-F854-7F68-3189-9713576A967C',6.0,'DEBBIE ROBINSON','DIRECTOR OF PURCHASING','UNIVERSITY OF HIGHER ED SOUTH BEND','PURCHASING SERVICES','13 ELM STREET','BOISE','ID','88777','US','Y')
/
INSERT INTO PUR_AP_CMP_PARM_T (CAMPUS_CD,OBJ_ID,VER_NBR,CMP_PUR_DRCTR_NM,CMP_PUR_DRCTR_TTL,PUR_INST_NM,PUR_DEPT_NM,PUR_DEPT_LN1_ADDR,PUR_DEPT_CTY_NM,PUR_DEPT_ST_CD,PUR_DEPT_ZIP_CD,PUR_DEPT_CNTRY_CD,ACTV_IND)
  VALUES ('SE','A0F1930D-0979-521F-F501-721F40A9F07A',8.0,'MICHAEL KLIEN','DIRECTOR OF PURCHASING','UNIVERSITY OF NEW ALBANY','PURCHASING DEPARTMENT','789 ROGERS ROAD','CAPITAL CITY','WY','88334','US','Y')
/
