#!/bin/sh
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.1 -Ddeployment.artifactId=classes12 -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.1/classes12.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.1 -Ddeployment.artifactId=classes12_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.1/classes12_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.1 -Ddeployment.artifactId=classes12dms -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.1/classes12dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.1 -Ddeployment.artifactId=classes12dms_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.1/classes12dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.1 -Ddeployment.artifactId=ojdbc14 -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.1/ojdbc14.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.1 -Ddeployment.artifactId=ojdbc14_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.1/ojdbc14_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.1 -Ddeployment.artifactId=ojdbc14dms -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.1/ojdbc14dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.1 -Ddeployment.artifactId=ojdbc14dms_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.1/ojdbc14dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.1 -Ddeployment.artifactId=ons -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.1/ons.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.2 -Ddeployment.artifactId=classes12 -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.2/classes12.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.2 -Ddeployment.artifactId=classes12_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.2/classes12_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.2 -Ddeployment.artifactId=classes12dms -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.2/classes12dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.2 -Ddeployment.artifactId=classes12dms_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.2/classes12dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.2 -Ddeployment.artifactId=ojdbc14 -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.2/ojdbc14.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.2 -Ddeployment.artifactId=ojdbc14_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.2/ojdbc14_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.2 -Ddeployment.artifactId=ojdbc14dms -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.2/ojdbc14dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.2 -Ddeployment.artifactId=ojdbc14dms_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.2/ojdbc14dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.2 -Ddeployment.artifactId=ons -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.2/ons.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.2 -Ddeployment.artifactId=orai18n -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.2/orai18n.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.3 -Ddeployment.artifactId=classes12 -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.3/classes12.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.3 -Ddeployment.artifactId=classes12_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.3/classes12_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.3 -Ddeployment.artifactId=classes12dms -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.3/classes12dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.3 -Ddeployment.artifactId=classes12dms_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.3/classes12dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.3 -Ddeployment.artifactId=ojdbc14 -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.3/ojdbc14.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.3 -Ddeployment.artifactId=ojdbc14_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.3/ojdbc14_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.3 -Ddeployment.artifactId=ojdbc14dms -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.3/ojdbc14dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.3 -Ddeployment.artifactId=ojdbc14dms_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.3/ojdbc14dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.3 -Ddeployment.artifactId=ons -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.3/ons.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.3 -Ddeployment.artifactId=orai18n -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.3/orai18n.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.4 -Ddeployment.artifactId=classes12 -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.4/classes12.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.4 -Ddeployment.artifactId=classes12_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.4/classes12_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.4 -Ddeployment.artifactId=classes12dms -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.4/classes12dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.4 -Ddeployment.artifactId=classes12dms_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.4/classes12dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.4 -Ddeployment.artifactId=ojdbc14 -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.4/ojdbc14.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.4 -Ddeployment.artifactId=ojdbc14_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.4/ojdbc14_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.4 -Ddeployment.artifactId=ojdbc14dms -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.4/ojdbc14dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.4 -Ddeployment.artifactId=ojdbc14dms_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.4/ojdbc14dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.4 -Ddeployment.artifactId=orai18n -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.4/orai18n.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.5 -Ddeployment.artifactId=classes12 -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.5/classes12.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.5 -Ddeployment.artifactId=classes12_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.5/classes12_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.5 -Ddeployment.artifactId=classes12dms -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.5/classes12dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.5 -Ddeployment.artifactId=classes12dms_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.5/classes12dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.5 -Ddeployment.artifactId=ojdbc14 -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.5/ojdbc14.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.5 -Ddeployment.artifactId=ojdbc14_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.5/ojdbc14_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.5 -Ddeployment.artifactId=ojdbc14dms -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.5/ojdbc14dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=10.2.0.5 -Ddeployment.artifactId=ojdbc14dms_g -Ddeployment.file=/home/ubuntu/.oracle/10.2.0.5/ojdbc14dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.6 -Ddeployment.artifactId=ojdbc5 -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.6/ojdbc5.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.6 -Ddeployment.artifactId=ojdbc5_g -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.6/ojdbc5_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.6 -Ddeployment.artifactId=ojdbc6 -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.6/ojdbc6.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.6 -Ddeployment.artifactId=ojdbc6_g -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.6/ojdbc6_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.6 -Ddeployment.artifactId=orai18n -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.6/orai18n.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.7 -Ddeployment.artifactId=ojdbc5 -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.7/ojdbc5.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.7 -Ddeployment.artifactId=ojdbc5_g -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.7/ojdbc5_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.7 -Ddeployment.artifactId=ojdbc5dms -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.7/ojdbc5dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.7 -Ddeployment.artifactId=ojdbc5dms_g -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.7/ojdbc5dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.7 -Ddeployment.artifactId=ojdbc6 -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.7/ojdbc6.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.7 -Ddeployment.artifactId=ojdbc6_g -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.7/ojdbc6_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.7 -Ddeployment.artifactId=ojdbc6dms -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.7/ojdbc6dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.7 -Ddeployment.artifactId=ojdbc6dms_g -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.7/ojdbc6dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.1.0.7 -Ddeployment.artifactId=orai18n -Ddeployment.file=/home/ubuntu/.oracle/11.1.0.7/orai18n.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.1 -Ddeployment.artifactId=ojdbc5 -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.1/ojdbc5.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.1 -Ddeployment.artifactId=ojdbc5_g -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.1/ojdbc5_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.1 -Ddeployment.artifactId=ojdbc5dms -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.1/ojdbc5dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.1 -Ddeployment.artifactId=ojdbc5dms_g -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.1/ojdbc5dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.1 -Ddeployment.artifactId=ojdbc6 -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.1/ojdbc6.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.1 -Ddeployment.artifactId=ojdbc6_g -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.1/ojdbc6_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.1 -Ddeployment.artifactId=ojdbc6dms -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.1/ojdbc6dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.1 -Ddeployment.artifactId=ojdbc6dms_g -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.1/ojdbc6dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.1 -Ddeployment.artifactId=orai18n -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.1/orai18n.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.2 -Ddeployment.artifactId=ojdbc5 -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.2/ojdbc5.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.2 -Ddeployment.artifactId=ojdbc5_g -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.2/ojdbc5_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.2 -Ddeployment.artifactId=ojdbc5dms -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.2/ojdbc5dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.2 -Ddeployment.artifactId=ojdbc5dms_g -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.2/ojdbc5dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.2 -Ddeployment.artifactId=ojdbc6 -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.2/ojdbc6.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.2 -Ddeployment.artifactId=ojdbc6_g -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.2/ojdbc6_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.2 -Ddeployment.artifactId=ojdbc6dms -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.2/ojdbc6dms.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.2 -Ddeployment.artifactId=ojdbc6dms_g -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.2/ojdbc6dms_g.jar
mvn process-resources -Pprivate -Ddeployment.groupId=com.oracle -Ddeployment.version=11.2.0.2 -Ddeployment.artifactId=orai18n -Ddeployment.file=/home/ubuntu/.oracle/11.2.0.2/orai18n.jar
