-- FOO
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FOO'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -00942 THEN RAISE; END IF; END;
/

CREATE TABLE FOO (CMPNT_SET_ID VARCHAR2(40)
        , LAST_UPDT_TS DATE NOT NULL
        , CHKSM VARCHAR2(40) NOT NULL
        , VER_NBR NUMBER(8) default 0 NOT NULL
)
/

ALTER TABLE FOO ADD CONSTRAINT FOO_P1 PRIMARY KEY (CMPNT_SET_ID)
/

-- BAR
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BAR'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -00942 THEN RAISE; END IF; END;
/

CREATE TABLE BAR (NMSPC_CD VARCHAR2(20)
        , CMPNT_CD VARCHAR2(100)
        , OBJ_ID VARCHAR2(36) default SYS_GUID() NOT NULL
        , VER_NBR NUMBER(8) default 1 NOT NULL
        , NM VARCHAR2(255)
        , ACTV_IND CHAR(1) default 'Y' NOT NULL
    , CONSTRAINT BAR_U1 UNIQUE (OBJ_ID)
)
/

ALTER TABLE BAR ADD CONSTRAINT BAR_P1 PRIMARY KEY (NMSPC_CD,CMPNT_CD)
/
