package org.kuali.maven.plugins.ecl.filter;

public class MultipleCopyrightIgnoresFilter extends CommonIgnoresFilter {

    public MultipleCopyrightIgnoresFilter() {
        super();
        excludes.add("/impl/src/main/resources/schema/ApplicationConstants.xsd");
        excludes.add("/impl/src/main/resources/schema/common.xsd");
        excludes.add("/impl/src/main/resources/schema/DocumentType.xsd");
        excludes.add("/impl/src/main/resources/schema/EDocLite.xsd");
        excludes.add("/impl/src/main/resources/schema/EDocLiteDef.xsd");
        excludes.add("/impl/src/main/resources/schema/Group.xsd");
        excludes.add("/impl/src/main/resources/schema/ResolverConfig.xsd");
        excludes.add("/impl/src/main/resources/schema/RoutingConfig.xsd");
        excludes.add("/impl/src/main/resources/schema/Rule.xsd");
        excludes.add("/impl/src/main/resources/schema/RuleAttribute.xsd");
        excludes.add("/impl/src/main/resources/schema/RuleDelegation.xsd");
        excludes.add("/impl/src/main/resources/schema/RuleTemplate.xsd");
        excludes.add("/impl/src/main/resources/schema/schema-for-xslt20.xsd");
        excludes.add("/impl/src/main/resources/schema/SearchingConfig.xsd");
        excludes.add("/impl/src/main/resources/schema/Style.xsd");
        excludes.add("/impl/src/main/resources/schema/User.xsd");
        excludes.add("/impl/src/main/resources/schema/WorkflowData.xsd");
        excludes.add("/src/site/docbook/IG/appendix_dbms.xml");
        excludes.add("/src/site/docbook/IG/intro.xml");
        excludes.add("/src/site/docbook/TRG/TRG_KEN.xml");
        excludes.add("/src/site/docbook/UG/UG_Global.xml");
        excludes.add("/scripts/jpaconversion/AnnotationHandler.groovy");
        excludes.add("/scripts/jpaconversion/archives/ojb2jpa.groovy");
        excludes.add("/scripts/jpaconversion/refactor/AnnotationHandler.groovy");
        excludes.add("/scripts/jpaconversion/AnnotationHandler.groovy");
        excludes.add("/impl/src/main/java/org/kuali/rice/kew/exception/WorkflowServiceErrorImpl.java");
        excludes.add("/kew/framework/src/main/java/org/kuali/rice/kew/framework/postprocessor/DocumentRouteLevelChange.java");
        excludes.add("/kew/framework/src/main/java/org/kuali/rice/kew/framework/postprocessor/DocumentRouteStatusChange.java");
        excludes.add("/krad/krad-web-framework/src/main/java/org/kuali/rice/krad/uif/view/View.java");
        excludes.add("/krad/krad-web-framework/src/main/resources/org/kuali/rice/krad/ApplicationResources.properties");
        excludes.add("notification.css");
        excludes.add("/web/src/main/webapp/kr/css/kuali.css");
        excludes.add("/web/src/main/webapp/ken/scripts/jscalendar-1.0/skins/aqua/theme.css");
        excludes.add("/web/src/main/webapp/kr/scripts/jscalendar-1.0/skins/aqua/theme.css");
        excludes.add("/web/src/main/webapp/krad/css/global/base.css");
        excludes.add("/web/src/main/webapp/krad/css/global/fss-reset.css");
        excludes.add("/web/src/main/webapp/krad/css/global/jquery/jquery-ui-1.8.11.css");
        excludes.add("/web/src/main/webapp/krad/css/global/tabs.css");
        excludes.add("/web/src/main/webapp/krad/css/kns/jquery-ui-1.8.11.css");
        excludes.add("/web/src/main/webapp/rice-portal/css/portal.css");
        excludes.add("/web/src/main/webapp/kew/css/kuali.css");
        excludes.add("/web/src/main/webapp/kew/scripts/cal2.js");
        excludes.add("/web/src/main/webapp/kr/scripts/dhtml.js");
        excludes.add("/web/src/main/webapp/krad/scripts/jquery/jquery-1.6.3.js");
        excludes.add("/web/src/main/webapp/krad/scripts/jquery/jquery-ui-1.8.9.js");
        excludes.add("/web/src/main/webapp/krad/scripts/jquery/jquery.ba-postmessage.js");
        excludes.add("/web/src/main/webapp/krad/scripts/jquery/jquery.blockUI.js");
        excludes.add("/web/src/main/webapp/krad/scripts/jquery/jquery.dirtyform.js");
        excludes.add("/web/src/main/webapp/krad/scripts/jquery/jquery.easing-1.3.pack.js");
        excludes.add("/web/src/main/webapp/krad/scripts/jquery/jquery.watermark.js");
        excludes.add("/LICENSE.txt");
        excludes.add("/NOTICE.txt");
        excludes.add("/web/src/main/webapp/acknowledgments.jsp");
        excludes.add("/web/src/main/webapp/kim/index.jsp");
        excludes.add("/web/src/main/webapp/ksb/WEB-INF/jsp/Footer.jsp");
        excludes.add("/web/src/main/webapp/ken/scripts/jscalendar-1.0/release-notes.html");
        excludes.add("/web/src/main/webapp/kr/scripts/jscalendar-1.0/release-notes.html");
    }
}
