#!/bin/bash
set -x
su - tomcat /usr/local/tomcat/bin/forced-shutdown.sh
set -e
cd /root/kuali-ec2
svn update
mci
mcp -Ptomcat,${env.TOMCATVERSION},medium
cd /root/kuali-dns
svn update
mci
mvn dnsme:addrecord -Ddnsme.recordName=${env.DNSFRAGMENT} -Ddnsme.recordValue=$PUBLICHOSTNAME
