#!/bin/sh

#
# This script is used to run other shell scripts once (and only once)
# It looks for shell scripts in a pre-defined directory, executes them,
# then moves them to another directory so they are never executed again
#


for file in /etc/local/runonce.d/*
do
    if [[ ! -f "$file" ]]
    then
        continue
    fi
    "$file"
    filename=$(basename $file)
    mv $file /usr/local/runonce.d/ran/$filename.$(date +%Y%m%dT%H%M%S)
    logger -t runonce -p local3.info "$file"
done