#!/bin/sh
for file in /etc/local/runonce.d/*
do
    if [[ ! -f "$file" ]]
    then
        continue
    fi
    "$file"
    filename=$(basename $file)
    mv $file /usr/local/runonce.d/ran/$filename.$(date +%Y%m%dT%H%M%S)
    logger -t runonce -p local3.info "$file"
done