#!/bin/bash
set -x
su - tomcat /usr/local/tomcat/bin/forced-shutdown.sh
set -e
cd /root/kuali-ec2
svn update
mci
mcp -Ptomcat,${tomcat.version},medium
cd /root/kuali-dns
svn update
mci
PUBLICHOSTNAME=$(GET http://169.254.169.254/latest/meta-data/public-hostname) 
mvn dnsme:addrecord -Ddnsme.recordName=${dns.prefix} -Ddnsme.recordValue=$PUBLICHOSTNAME
