package org.kuali.common.jalc.model.compare;

public enum TableDifferenceType {
    TABLE_DESCRIPTION, COLUMN_DATA_TYPE, COLUMN_PRIMARY_KEY, COLUMN_NULLABLE, COLUMN_DATA_TYPE_SIZE, COLUMN_DESCRIPTION, COLUMN_DEFAULT_VALUE, UNIQUE_CONSTRAINT_COLUMNS, MISSING_UNIQUE_CONSTRAINT, MISSING_INDEX, MISSING_COLUMN, INDEX_COLUMNS, INDEX_UNIQUE, MISSING_TABLE


}
