#!/bin/sh

echo $(date)
set -xe

if [ $# -ne 1 ]; then
   if [ -z "${JENKINS_MASTER}" ] ; then
     echo "Please set JENKINS_MASTER"
     exit 1
   fi
else
  JENKINS_MASTER=$1
fi

# The trailing slash is significant here
SRC=/root/.m2/repository/
DST=jenkins@${JENKINS_MASTER}:/var/lib/jenkins/m2/repository
EXCLUDEFILE=/root/kuali-ec2/src/main/resources/jenkins/slave/rsync-excludes

# Make the rsync call
rsync --archive --stats -v $SRC $DST --exclude-from $EXCLUDEFILE

set +x
echo $(date)
