#!/bin/sh

set -xe

if [ -z "${JOB_NAME}" ]; then
  echo "Please set JOB_NAME"
  exit 1
fi

JOB_TO_COPY=$1

if [ -z "${JOB_TO_COPY}" ]; then
  JOB_TO_COPY=$JOB_NAME
fi

cd /root/kuali-ec2/src/main/resources/jenkins/slave

#
# Error code 23 is what rsync returns if there is no workspace on the master yet
# There won't be a workspace on the master until after the job has run to completion successfully at least once
# and the sync-to-master script has successfully completed
#

mvn -Psync-from-master jenkins:syncworkspace -Djenkins.job=$JOB_TO_COPY -Djenkins.excludeTarget=false -Djenkins.ignoreCodes=23
