CREATE TABLE FOO_T
(
      ID VARCHAR2(36)
        , CREATETIME TIMESTAMP NOT NULL
        , NAME VARCHAR2(255)

)
/
ALTER TABLE FOO_T
    ADD CONSTRAINT FOO_TP1
PRIMARY KEY (ID)
/

CREATE TABLE BAR_T
(
      ID VARCHAR2(36)
        , CREATETIME TIMESTAMP NOT NULL
        , NAME VARCHAR2(255)
        , FOO_ID VARCHAR2(36)
)
/
ALTER TABLE BAR_T
    ADD CONSTRAINT BAR_TP1
PRIMARY KEY (ID)
/

CREATE TABLE BAZ_T
(
      ID VARCHAR2(36)
        , XML CLOB NOT NULL
        , CREATETIME TIMESTAMP NOT NULL
        , NAME VARCHAR2(255)
        , FOO_ID VARCHAR2(36)
)
/
ALTER TABLE BAZ_T
    ADD CONSTRAINT BAZ_TP1
PRIMARY KEY (ID)
/

-- complex clob example:  2 pks, 2 clob columns
CREATE TABLE COMPLEX_BAZ_T
(
      ID_ONE VARCHAR2(36)
        , ID_TWO VARCHAR2(36)
        , XML CLOB NOT NULL
        , COMPLEX_DATA CLOB NOT NULL
        , CREATETIME TIMESTAMP NOT NULL
        , NAME VARCHAR2(255)
        , FOO_ID VARCHAR2(36)
)
/
ALTER TABLE COMPLEX_BAZ_T
    ADD CONSTRAINT COMPLEX_BAZ_TP1
PRIMARY KEY (ID_ONE,ID_TWO)
/