#!/bin/sh -x

function kdailytaghead {
    {
        branch=HEAD
        new_build_tag="kra-HEAD"
        klog "tagging branch: $branch of application java and database modules with new_build_tag: $new_build_tag"
        kexec "cvs -q rtag -d $new_build_tag $APPLICATION_JAVA_CVS_MODULE"
        kexec "cvs -q rtag -r $branch $new_build_tag $APPLICATION_JAVA_CVS_MODULE"
        kexec "cvs -q rtag -d $new_build_tag $APPLICATION_DATABASE_CVS_MODULE"
        kexec "cvs -q rtag $new_build_tag $APPLICATION_DATABASE_CVS_MODULE"
        return 0
    } >> $SCRIPT_LOG 2>&1
}
typeset -xf kdailytaghead

function kdailytagsvn {
    {
        branch=$1
        old_build_number=`cat svn-build-number.txt`
        new_build_number=`expr $old_build_number + 1`
        new_build_tag="build-"$branch"-"$new_build_number
        kexec "echo $new_build_number > svn-build-number.txt"
        tag_message="daily tag"
        klog "tagging branch: $branch of application java and database modules with new_build_tag: $new_build_tag"
        kexec "svn copy http://test.kuali.org/kra_1-1/trunk http://test.kuali.org/kra_1-1/branches/$new_build_tag -m $tag_message"
        kexec "cvs -q rtag -d $new_build_tag $APPLICATION_DATABASE_CVS_MODULE"
        kexec "cvs -q rtag $new_build_tag $APPLICATION_DATABASE_CVS_MODULE"
        return 0
    } >> $SCRIPT_LOG 2>&1
}
typeset -xf kdailytagsvn

function runS2sScripts {
  typeset environment=$1
  typeset password=$environment"174kra"
  klog "running S2S scripts in: $environment"
  export ORACLE_HOME=/opt/oracle/product/current
  kexec "sqlplus kra$environment/$password@kuali @/home/j2eemgr/kuali/kra/S2S-Release1.0/S2S-Release1.sql"
}
typeset -xf runS2sScripts

function buildsvnwebapp {
  typeset environment=$1
  kexec "/usr/local/bin/appdeploy kra $environment"
}
typeset -xf buildsvnwebapp
