#!/bin/bash
#
# Output from this script gets logged to /var/log/cloud-init.log
#
set -xe
svn co https://svn.kuali.org/repos/foundation/trunk/kuali-ec2 /root/kuali-ec2
cd /root/kuali-ec2
MVN=/opt/asf/mvn/bin/mvn
$MVN clean install
$MVN clean process-resources -Ptomcat,${tomcat.version},medium -Djdk.version=${jdk.version}
$MVN clean process-resources -Pappdynamics
