INSERT INTO KRCR_CMPNT_SET_T (CMPNT_SET_ID, LAST_UPDT_TS, CHKSM, VER_NBR) VALUES ('1',SYSDATE,'abc',17)
/

INSERT INTO KRCR_CMPNT_SET_T (CMPNT_SET_ID, LAST_UPDT_TS, CHKSM, VER_NBR) VALUES ('2',SYSDATE,'def',27)
/

INSERT INTO KRCR_CMPNT_SET_T (CMPNT_SET_ID, LAST_UPDT_TS, CHKSM, VER_NBR) VALUES ('3',SYSDATE,'ghi',37)
/
