#!/bin/bash
# /etc/init.d/ec2slave
# debian-compatible ec2slave init script.
# Jeff Caddel <jcaddel@kuali.org>
#
### BEGIN INIT INFO
# Provides:          ec2slave 
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Perform Elastic CI slave tasks 
# Description:       Perform Elastic CI slave tasks  
### END INIT INFO

case "$1" in
  start)
    echo "Starting Elastic CI Slave - $(date)"
    svn up /root/kuali-ec2
    exec /root/kuali-ec2/src/main/resources/jenkins/slave/init-script
    ;;
  stop)
    echo "Stopping Elastic CI Slave - $(date)"
    svn up /root/kuali-ec2
    exec /root/kuali-ec2/src/main/resources/jenkins/slave/shutdown-script
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop}" >&2
    exit 3
    ;;
esac

exit 0
