#!/bin/sh -xe


if [ $# -ne 1 ]; then
  echo "Usage: $0 job-to-copy"
  exit 1
fi

if [ -z "${JOB_NAME}" ]; then
  echo "Please set JOB_NAME"
  exit 1
fi

LCL_WS=/var/lib/jenkins/workspace/$JOB_NAME
RMT_WS=/var/lib/jenkins/jobs/$1/workspace

SRC=jenkins@ci.rice.kuali.org:$RMT_WS/
DST=$LCL_WS

# Skip compressing files we know are compressed already
SC=jar,war,zip,gz,bz2,png,jpg,jpeg,gif,ico

echo $(date)
rsync -avhz --skip-compress=$SC --rsh=ssh --delete $SRC $DST
echo $(date)
