#!/bin/sh -xe

if [ -z "${JOB_NAME}" ] ; then
  echo "Please set JOB_NAME"
  exit 1
fi

LCL_WS=/var/lib/jenkins/workspace/$JOB_NAME
RMT_WS=/var/lib/jenkins/jobs/$JOB_NAME/workspace

SRC=$LCL_WS/
DST=jenkins@ci.rice.kuali.org:$RMT_WS

# Skip compressing files we know are compressed already
SC=jar,war,zip,gz,bz2,png,jpg,jpeg,gif,ico

echo $(date)
chown -R jenkins:ubuntu $LCL_WS
rsync -avhz --skip-compress=$SC --rsh=ssh --delete $SRC $DST
echo $(date)
