#!/bin/sh

# init script for slave instances referenced in /etc/rc.local
# output is logged to /var/boot.log

echo $(date)
set -xe

scp root@ci.rice.kuali.org:/var/lib/jenkins/.m2/settings.xml /root/.m2/settings.xml
/root/kuali-ec2/src/main/resources/jenkins/slave/copy-repo-from-master

set +x
echo $(date)
