#!/bin/sh

#
#
# This shell script gets executed by slave instances at startup
# /etc/rc.local on the slaves updates to the latest from Subversion
# then executes this script
#
#

echo $(date)
set -xe

scp root@ci.rice.kuali.org:/var/lib/jenkins/.m2/settings.xml /root/.m2/settings.xml

set +x
echo $(date)
