#!/bin/sh

# shutdown script for slave instances
# output is logged to /var/log/boot.log

echo $(date)
set -xe

/root/kuali-ec2/src/main/resources/jenkins/slave/copy-repo-to-master ci.rice.kuali.org

set +x
echo $(date)
