#!/bin/sh

set -xe

if [ -z "${JOB_NAME}" ]; then
  echo "Please set JOB_NAME"
  exit 1
fi

JOB_TO_COPY=$1

if [ -z "${JOB_TO_COPY}" ]; then
  JOB_TO_COPY=$JOB_NAME
fi

M2_HOME="/var/lib/jenkins/tools/Maven-3.0.3"
MVN=$M2_HOME/bin/mvn

cd /root/kuali-ec2/src/main/resources/jenkins/slave

$MVN clean -Psync-from-master jenkins:syncworkspace -Djenkins.job=$JOB_TO_COPY -Djenkins.excludeTarget=false
