#!/bin/sh

set -xe

M2_HOME="/var/lib/jenkins/tools/Maven-3.0.3"
MVN=$M2_HOME/bin/mvn

cd /root/kuali-ec2/src/main/resources/jenkins/slave

$MVN -Psync-to-master jenkins:syncworkspace -Djenkins.excludeTarget=false -Djenkins.verbose=true
