//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 05:43:49 PM MST 
//


package org.kuali.common.log.log4j.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "log4JEvent"
})
@XmlRootElement(name = "log4j:eventSet")
public class Log4JEventSet {

    @XmlAttribute(name = "xmlns:log4j")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlnsLog4J;
    @XmlAttribute(name = "version")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "includesLocationInfo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String includesLocationInfo;
    @XmlElement(name = "log4j:event")
    protected List<Log4JEvent> log4JEvent;

    /**
     * Gets the value of the xmlnsLog4J property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsLog4J() {
        if (xmlnsLog4J == null) {
            return "http://jakarta.apache.org/log4j/";
        } else {
            return xmlnsLog4J;
        }
    }

    /**
     * Sets the value of the xmlnsLog4J property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsLog4J(String value) {
        this.xmlnsLog4J = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.2";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the includesLocationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludesLocationInfo() {
        if (includesLocationInfo == null) {
            return "true";
        } else {
            return includesLocationInfo;
        }
    }

    /**
     * Sets the value of the includesLocationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludesLocationInfo(String value) {
        this.includesLocationInfo = value;
    }

    /**
     * Gets the value of the log4JEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the log4JEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLog4JEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Log4JEvent }
     * 
     * 
     */
    public List<Log4JEvent> getLog4JEvent() {
        if (log4JEvent == null) {
            log4JEvent = new ArrayList<Log4JEvent>();
        }
        return this.log4JEvent;
    }

}
