//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 05:43:49 PM MST 
//


package org.kuali.common.log.log4j.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kuali.common.log.log4j.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kuali.common.log.log4j.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Log4JEvent }
     * 
     */
    public Log4JEvent createLog4JEvent() {
        return new Log4JEvent();
    }

    /**
     * Create an instance of {@link Log4JLocationInfo }
     * 
     */
    public Log4JLocationInfo createLog4JLocationInfo() {
        return new Log4JLocationInfo();
    }

    /**
     * Create an instance of {@link Log4JProperties }
     * 
     */
    public Log4JProperties createLog4JProperties() {
        return new Log4JProperties();
    }

    /**
     * Create an instance of {@link DataSource }
     * 
     */
    public DataSource createDataSource() {
        return new DataSource();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Priority }
     * 
     */
    public Priority createPriority() {
        return new Priority();
    }

    /**
     * Create an instance of {@link Level }
     * 
     */
    public Level createLevel() {
        return new Level();
    }

    /**
     * Create an instance of {@link AppenderRef }
     * 
     */
    public AppenderRef createAppenderRef() {
        return new AppenderRef();
    }

    /**
     * Create an instance of {@link Log4JData }
     * 
     */
    public Log4JData createLog4JData() {
        return new Log4JData();
    }

    /**
     * Create an instance of {@link Log4JConfiguration }
     * 
     */
    public Log4JConfiguration createLog4JConfiguration() {
        return new Log4JConfiguration();
    }

    /**
     * Create an instance of {@link Renderer }
     * 
     */
    public Renderer createRenderer() {
        return new Renderer();
    }

    /**
     * Create an instance of {@link Appender }
     * 
     */
    public Appender createAppender() {
        return new Appender();
    }

    /**
     * Create an instance of {@link Plugin }
     * 
     */
    public Plugin createPlugin() {
        return new Plugin();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Logger }
     * 
     */
    public Logger createLogger() {
        return new Logger();
    }

    /**
     * Create an instance of {@link CategoryFactory }
     * 
     */
    public CategoryFactory createCategoryFactory() {
        return new CategoryFactory();
    }

    /**
     * Create an instance of {@link LoggerFactory }
     * 
     */
    public LoggerFactory createLoggerFactory() {
        return new LoggerFactory();
    }

    /**
     * Create an instance of {@link ErrorHandler }
     * 
     */
    public ErrorHandler createErrorHandler() {
        return new ErrorHandler();
    }

    /**
     * Create an instance of {@link RootRef }
     * 
     */
    public RootRef createRootRef() {
        return new RootRef();
    }

    /**
     * Create an instance of {@link LoggerRef }
     * 
     */
    public LoggerRef createLoggerRef() {
        return new LoggerRef();
    }

    /**
     * Create an instance of {@link Log4JEventSet }
     * 
     */
    public Log4JEventSet createLog4JEventSet() {
        return new Log4JEventSet();
    }

    /**
     * Create an instance of {@link RollingPolicy }
     * 
     */
    public RollingPolicy createRollingPolicy() {
        return new RollingPolicy();
    }

    /**
     * Create an instance of {@link ConnectionSource }
     * 
     */
    public ConnectionSource createConnectionSource() {
        return new ConnectionSource();
    }

    /**
     * Create an instance of {@link Layout }
     * 
     */
    public Layout createLayout() {
        return new Layout();
    }

    /**
     * Create an instance of {@link TriggeringPolicy }
     * 
     */
    public TriggeringPolicy createTriggeringPolicy() {
        return new TriggeringPolicy();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

}
