//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 05:43:49 PM MST 
//


package org.kuali.common.log.log4j.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "log4JMessage",
    "log4JNDC",
    "log4JThrowable",
    "log4JLocationInfo",
    "log4JProperties"
})
@XmlRootElement(name = "log4j:event")
public class Log4JEvent {

    @XmlAttribute(name = "logger", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String logger;
    @XmlAttribute(name = "level", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String level;
    @XmlAttribute(name = "thread", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String thread;
    @XmlAttribute(name = "timestamp", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String timestamp;
    @XmlAttribute(name = "time")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String time;
    @XmlElement(name = "log4j:message", required = true)
    protected String log4JMessage;
    @XmlElement(name = "log4j:NDC")
    protected String log4JNDC;
    @XmlElement(name = "log4j:throwable")
    protected String log4JThrowable;
    @XmlElement(name = "log4j:locationInfo")
    protected Log4JLocationInfo log4JLocationInfo;
    @XmlElement(name = "log4j:properties")
    protected Log4JProperties log4JProperties;

    /**
     * Gets the value of the logger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogger() {
        return logger;
    }

    /**
     * Sets the value of the logger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogger(String value) {
        this.logger = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the thread property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThread() {
        return thread;
    }

    /**
     * Sets the value of the thread property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThread(String value) {
        this.thread = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the log4JMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLog4JMessage() {
        return log4JMessage;
    }

    /**
     * Sets the value of the log4JMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLog4JMessage(String value) {
        this.log4JMessage = value;
    }

    /**
     * Gets the value of the log4JNDC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLog4JNDC() {
        return log4JNDC;
    }

    /**
     * Sets the value of the log4JNDC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLog4JNDC(String value) {
        this.log4JNDC = value;
    }

    /**
     * Gets the value of the log4JThrowable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLog4JThrowable() {
        return log4JThrowable;
    }

    /**
     * Sets the value of the log4JThrowable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLog4JThrowable(String value) {
        this.log4JThrowable = value;
    }

    /**
     * Gets the value of the log4JLocationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Log4JLocationInfo }
     *     
     */
    public Log4JLocationInfo getLog4JLocationInfo() {
        return log4JLocationInfo;
    }

    /**
     * Sets the value of the log4JLocationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Log4JLocationInfo }
     *     
     */
    public void setLog4JLocationInfo(Log4JLocationInfo value) {
        this.log4JLocationInfo = value;
    }

    /**
     * Gets the value of the log4JProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Log4JProperties }
     *     
     */
    public Log4JProperties getLog4JProperties() {
        return log4JProperties;
    }

    /**
     * Sets the value of the log4JProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Log4JProperties }
     *     
     */
    public void setLog4JProperties(Log4JProperties value) {
        this.log4JProperties = value;
    }

}
