//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 05:43:49 PM MST 
//


package org.kuali.common.log.log4j.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "renderer")
public class Renderer {

    @XmlAttribute(name = "renderedClass", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String renderedClass;
    @XmlAttribute(name = "renderingClass", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String renderingClass;

    /**
     * Gets the value of the renderedClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenderedClass() {
        return renderedClass;
    }

    /**
     * Sets the value of the renderedClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenderedClass(String value) {
        this.renderedClass = value;
    }

    /**
     * Gets the value of the renderingClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenderingClass() {
        return renderingClass;
    }

    /**
     * Sets the value of the renderingClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenderingClass(String value) {
        this.renderingClass = value;
    }

}
