package org.kuali.common.jdbc;

/**
 *
 * This works for SQL files generated by <code>mysqldump</code>. <code>mysqldump</code> files have the following characteristics that allow
 * this to work:<br>
 * 1 - Every individual SQL statement is on a single line. SQL containing carriage returns and linefeeds (html text for example) is escaped
 * and still contained on a single line<br>
 * 2 - Every individual SQL statement is ended with a semi-colon<br>
 *
 * Those 2 characteristics make parsing the SQL file a very trivial thing to do.
 */
public class MySQLDumpReader extends DefaultSqlReader {

	public MySQLDumpReader() {
		super();
		setDelimiter(";");
		setDelimiterMode(DelimiterMode.END_OF_LINE);
	}

}
