--
-- Copyright 2010-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE CG_PRPSL_PURPOSE_T
/
INSERT INTO CG_PRPSL_PURPOSE_T (CGPRPSL_PURPOSE_CD,OBJ_ID,VER_NBR,PRPSL_PURPOSE_DESC,ROW_ACTV_IND)
  VALUES ('A','12BF192103099D6CE043814FD8819D6C',1.0,'INSTRUCTION','Y')
/
INSERT INTO CG_PRPSL_PURPOSE_T (CGPRPSL_PURPOSE_CD,OBJ_ID,VER_NBR,PRPSL_PURPOSE_DESC,ROW_ACTV_IND)
  VALUES ('C','12BF1921030A9D6CE043814FD8819D6C',1.0,'RESEARCH','Y')
/
INSERT INTO CG_PRPSL_PURPOSE_T (CGPRPSL_PURPOSE_CD,OBJ_ID,VER_NBR,PRPSL_PURPOSE_DESC,ROW_ACTV_IND)
  VALUES ('F','12BF1921030B9D6CE043814FD8819D6C',1.0,'SERVICE/OTHER','Y')
/
INSERT INTO CG_PRPSL_PURPOSE_T (CGPRPSL_PURPOSE_CD,OBJ_ID,VER_NBR,PRPSL_PURPOSE_DESC,ROW_ACTV_IND)
  VALUES ('G','12BF1921030C9D6CE043814FD8819D6C',1.0,'ACADEMIC SUPPORT','Y')
/
INSERT INTO CG_PRPSL_PURPOSE_T (CGPRPSL_PURPOSE_CD,OBJ_ID,VER_NBR,PRPSL_PURPOSE_DESC,ROW_ACTV_IND)
  VALUES ('H','12BF1921030D9D6CE043814FD8819D6C',1.0,'STUDENT SERVICES','Y')
/
INSERT INTO CG_PRPSL_PURPOSE_T (CGPRPSL_PURPOSE_CD,OBJ_ID,VER_NBR,PRPSL_PURPOSE_DESC,ROW_ACTV_IND)
  VALUES ('S','12BF1921030E9D6CE043814FD8819D6C',1.0,'SCHOLARSHIPS & FELLOWSHIPS','Y')
/
INSERT INTO CG_PRPSL_PURPOSE_T (CGPRPSL_PURPOSE_CD,OBJ_ID,VER_NBR,PRPSL_PURPOSE_DESC,ROW_ACTV_IND)
  VALUES ('X','12BF1921030F9D6CE043814FD8819D6C',1.0,'DEFAULT','Y')
/
