--
-- Copyright 2010-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE FS_OPTION_T
/
INSERT INTO FS_OPTION_T (UNIV_FISCAL_YR,OBJ_ID,VER_NBR,ACT_FIN_BAL_TYP_CD,BDGT_CHK_BALTYP_CD,BDGT_CHK_OPTN_CD,UNIV_FSCYR_STRT_YR,UNIV_FSCYR_STRT_MO,FOBJTP_INC_CSH_CD,FOBJTP_XPND_EXP_CD,FOBJTP_XPNDNEXP_CD,FOBJTP_EXPNXPND_CD,FOBJ_TYP_ASSET_CD,FOBJ_TYP_LBLTY_CD,FOBJ_TYP_FNDBAL_CD,EXT_ENC_FBALTYP_CD,INT_ENC_FBALTYP_CD,PRE_ENC_FBALTYP_CD,ELIM_FINBAL_TYP_CD,FOBJTP_INC_NCSH_CD,FOBJTP_CSH_NINC_CD,UNIV_FIN_COA_CD,UNIV_FISCAL_YR_NM,FIN_BEGBALLOAD_IND,CSTSHR_ENCUM_FIN_BAL_TYP_CD,BASE_BDGT_FIN_BAL_TYP_CD,MO_BDGT_FIN_BAL_TYP_CD,FIN_OBJECT_TYP_TRNFR_INC_CD,FIN_OBJECT_TYP_TRNFR_EXP_CD,NMNL_FIN_BAL_TYP_CD)
  VALUES (2008.0,'682B40E65635B493E0404F8189D85FDE',1.0,'AC','CB','Y',2007.0,'07','IN','EX','EE','ES','AS','LI','FB','EX','IE','PE','TR','IC','CH','IU','2007-2008','Y','CE','BB','MB','TI','TE','NB')
/
INSERT INTO FS_OPTION_T (UNIV_FISCAL_YR,OBJ_ID,VER_NBR,ACT_FIN_BAL_TYP_CD,BDGT_CHK_BALTYP_CD,BDGT_CHK_OPTN_CD,UNIV_FSCYR_STRT_YR,UNIV_FSCYR_STRT_MO,FOBJTP_INC_CSH_CD,FOBJTP_XPND_EXP_CD,FOBJTP_XPNDNEXP_CD,FOBJTP_EXPNXPND_CD,FOBJ_TYP_ASSET_CD,FOBJ_TYP_LBLTY_CD,FOBJ_TYP_FNDBAL_CD,EXT_ENC_FBALTYP_CD,INT_ENC_FBALTYP_CD,PRE_ENC_FBALTYP_CD,ELIM_FINBAL_TYP_CD,FOBJTP_INC_NCSH_CD,FOBJTP_CSH_NINC_CD,UNIV_FIN_COA_CD,UNIV_FISCAL_YR_NM,FIN_BEGBALLOAD_IND,CSTSHR_ENCUM_FIN_BAL_TYP_CD,BASE_BDGT_FIN_BAL_TYP_CD,MO_BDGT_FIN_BAL_TYP_CD,FIN_OBJECT_TYP_TRNFR_INC_CD,FIN_OBJECT_TYP_TRNFR_EXP_CD,NMNL_FIN_BAL_TYP_CD)
  VALUES (2009.0,'903B13D9-D2D2-76C1-4749-9B0E8BE9B49B',1.0,'AC','CB','Y',2008.0,'07','IN','EX','EE','ES','AS','LI','FB','EX','IE','PE','TR','IC','CH','IU','2008-2009','Y','CE','BB','MB','TI','TE','NB')
/
INSERT INTO FS_OPTION_T (UNIV_FISCAL_YR,OBJ_ID,VER_NBR,ACT_FIN_BAL_TYP_CD,BDGT_CHK_BALTYP_CD,BDGT_CHK_OPTN_CD,UNIV_FSCYR_STRT_YR,UNIV_FSCYR_STRT_MO,FOBJTP_INC_CSH_CD,FOBJTP_XPND_EXP_CD,FOBJTP_XPNDNEXP_CD,FOBJTP_EXPNXPND_CD,FOBJ_TYP_ASSET_CD,FOBJ_TYP_LBLTY_CD,FOBJ_TYP_FNDBAL_CD,EXT_ENC_FBALTYP_CD,INT_ENC_FBALTYP_CD,PRE_ENC_FBALTYP_CD,ELIM_FINBAL_TYP_CD,FOBJTP_INC_NCSH_CD,FOBJTP_CSH_NINC_CD,UNIV_FIN_COA_CD,UNIV_FISCAL_YR_NM,FIN_BEGBALLOAD_IND,CSTSHR_ENCUM_FIN_BAL_TYP_CD,BASE_BDGT_FIN_BAL_TYP_CD,MO_BDGT_FIN_BAL_TYP_CD,FIN_OBJECT_TYP_TRNFR_INC_CD,FIN_OBJECT_TYP_TRNFR_EXP_CD,NMNL_FIN_BAL_TYP_CD)
  VALUES (2010.0,'4B52FB81-3B61-0E7B-07F2-9F5C418CC72A',1.0,'AC','CB','Y',2009.0,'07','IN','EX','EE','ES','AS','LI','FB','EX','IE','PE','TR','IC','CH','IU','2009-2010','N','CE','BB','MB','TI','TE','NB')
/
INSERT INTO FS_OPTION_T (UNIV_FISCAL_YR,OBJ_ID,VER_NBR,ACT_FIN_BAL_TYP_CD,BDGT_CHK_BALTYP_CD,BDGT_CHK_OPTN_CD,UNIV_FSCYR_STRT_YR,UNIV_FSCYR_STRT_MO,FOBJTP_INC_CSH_CD,FOBJTP_XPND_EXP_CD,FOBJTP_XPNDNEXP_CD,FOBJTP_EXPNXPND_CD,FOBJ_TYP_ASSET_CD,FOBJ_TYP_LBLTY_CD,FOBJ_TYP_FNDBAL_CD,EXT_ENC_FBALTYP_CD,INT_ENC_FBALTYP_CD,PRE_ENC_FBALTYP_CD,ELIM_FINBAL_TYP_CD,FOBJTP_INC_NCSH_CD,FOBJTP_CSH_NINC_CD,UNIV_FIN_COA_CD,UNIV_FISCAL_YR_NM,FIN_BEGBALLOAD_IND,CSTSHR_ENCUM_FIN_BAL_TYP_CD,BASE_BDGT_FIN_BAL_TYP_CD,MO_BDGT_FIN_BAL_TYP_CD,FIN_OBJECT_TYP_TRNFR_INC_CD,FIN_OBJECT_TYP_TRNFR_EXP_CD,NMNL_FIN_BAL_TYP_CD)
  VALUES (2011.0,'9177D6BE-A490-86C8-BA99-AAB76679A321',2.0,'AC','CB','Y',2010.0,'07','IN','EX','EE','ES','AS','LI','FB','EX','IE','PE','TR','IC','CH','IU','2010-2011','N','CE','BB','MB','TI','TE','NB')
/
INSERT INTO FS_OPTION_T (UNIV_FISCAL_YR,OBJ_ID,VER_NBR,ACT_FIN_BAL_TYP_CD,BDGT_CHK_BALTYP_CD,BDGT_CHK_OPTN_CD,UNIV_FSCYR_STRT_YR,UNIV_FSCYR_STRT_MO,FOBJTP_INC_CSH_CD,FOBJTP_XPND_EXP_CD,FOBJTP_XPNDNEXP_CD,FOBJTP_EXPNXPND_CD,FOBJ_TYP_ASSET_CD,FOBJ_TYP_LBLTY_CD,FOBJ_TYP_FNDBAL_CD,EXT_ENC_FBALTYP_CD,INT_ENC_FBALTYP_CD,PRE_ENC_FBALTYP_CD,ELIM_FINBAL_TYP_CD,FOBJTP_INC_NCSH_CD,FOBJTP_CSH_NINC_CD,UNIV_FIN_COA_CD,UNIV_FISCAL_YR_NM,FIN_BEGBALLOAD_IND,CSTSHR_ENCUM_FIN_BAL_TYP_CD,BASE_BDGT_FIN_BAL_TYP_CD,MO_BDGT_FIN_BAL_TYP_CD,FIN_OBJECT_TYP_TRNFR_INC_CD,FIN_OBJECT_TYP_TRNFR_EXP_CD,NMNL_FIN_BAL_TYP_CD)
  VALUES (2012.0,'CB0E3B2B-C339-4645-BC96-BDFA3E9CCDD8',2.0,'AC','CB','Y',2011.0,'07','IN','EX','EE','ES','AS','LI','FB','EX','IE','PE','TR','IC','CH','IU','2011-2012','N','CE','BB','MB','TI','TE','NB')
/
INSERT INTO FS_OPTION_T (UNIV_FISCAL_YR,OBJ_ID,VER_NBR,ACT_FIN_BAL_TYP_CD,BDGT_CHK_BALTYP_CD,BDGT_CHK_OPTN_CD,UNIV_FSCYR_STRT_YR,UNIV_FSCYR_STRT_MO,FOBJTP_INC_CSH_CD,FOBJTP_XPND_EXP_CD,FOBJTP_XPNDNEXP_CD,FOBJTP_EXPNXPND_CD,FOBJ_TYP_ASSET_CD,FOBJ_TYP_LBLTY_CD,FOBJ_TYP_FNDBAL_CD,EXT_ENC_FBALTYP_CD,INT_ENC_FBALTYP_CD,PRE_ENC_FBALTYP_CD,ELIM_FINBAL_TYP_CD,FOBJTP_INC_NCSH_CD,FOBJTP_CSH_NINC_CD,UNIV_FIN_COA_CD,UNIV_FISCAL_YR_NM,FIN_BEGBALLOAD_IND,CSTSHR_ENCUM_FIN_BAL_TYP_CD,BASE_BDGT_FIN_BAL_TYP_CD,MO_BDGT_FIN_BAL_TYP_CD,FIN_OBJECT_TYP_TRNFR_INC_CD,FIN_OBJECT_TYP_TRNFR_EXP_CD,NMNL_FIN_BAL_TYP_CD)
  VALUES (2013.0,'75C389C4-F85A-3CC2-2995-B2F4163EAA3C',2.0,'AC','CB','Y',2012.0,'07','IN','EX','EE','ES','AS','LI','FB','EX','IE','PE','TR','IC','CH','IU','2012-2013','N','CE','BB','MB','TI','TE','NB')
/
INSERT INTO FS_OPTION_T (UNIV_FISCAL_YR,OBJ_ID,VER_NBR,ACT_FIN_BAL_TYP_CD,BDGT_CHK_BALTYP_CD,BDGT_CHK_OPTN_CD,UNIV_FSCYR_STRT_YR,UNIV_FSCYR_STRT_MO,FOBJTP_INC_CSH_CD,FOBJTP_XPND_EXP_CD,FOBJTP_XPNDNEXP_CD,FOBJTP_EXPNXPND_CD,FOBJ_TYP_ASSET_CD,FOBJ_TYP_LBLTY_CD,FOBJ_TYP_FNDBAL_CD,EXT_ENC_FBALTYP_CD,INT_ENC_FBALTYP_CD,PRE_ENC_FBALTYP_CD,ELIM_FINBAL_TYP_CD,FOBJTP_INC_NCSH_CD,FOBJTP_CSH_NINC_CD,UNIV_FIN_COA_CD,UNIV_FISCAL_YR_NM,FIN_BEGBALLOAD_IND,CSTSHR_ENCUM_FIN_BAL_TYP_CD,BASE_BDGT_FIN_BAL_TYP_CD,MO_BDGT_FIN_BAL_TYP_CD,FIN_OBJECT_TYP_TRNFR_INC_CD,FIN_OBJECT_TYP_TRNFR_EXP_CD,NMNL_FIN_BAL_TYP_CD)
  VALUES (2014.0,'8d98aef7-d6bc-4443-8e9b-66cca04969a3',2.0,'AC','CB','Y',2013.0,'07','IN','EX','EE','ES','AS','LI','FB','EX','IE','PE','TR','IC','CH','IU','2013-2014','N','CE','BB','MB','TI','TE','NB')
/
INSERT INTO FS_OPTION_T (UNIV_FISCAL_YR,OBJ_ID,VER_NBR,ACT_FIN_BAL_TYP_CD,BDGT_CHK_BALTYP_CD,BDGT_CHK_OPTN_CD,UNIV_FSCYR_STRT_YR,UNIV_FSCYR_STRT_MO,FOBJTP_INC_CSH_CD,FOBJTP_XPND_EXP_CD,FOBJTP_XPNDNEXP_CD,FOBJTP_EXPNXPND_CD,FOBJ_TYP_ASSET_CD,FOBJ_TYP_LBLTY_CD,FOBJ_TYP_FNDBAL_CD,EXT_ENC_FBALTYP_CD,INT_ENC_FBALTYP_CD,PRE_ENC_FBALTYP_CD,ELIM_FINBAL_TYP_CD,FOBJTP_INC_NCSH_CD,FOBJTP_CSH_NINC_CD,UNIV_FIN_COA_CD,UNIV_FISCAL_YR_NM,FIN_BEGBALLOAD_IND,CSTSHR_ENCUM_FIN_BAL_TYP_CD,BASE_BDGT_FIN_BAL_TYP_CD,MO_BDGT_FIN_BAL_TYP_CD,FIN_OBJECT_TYP_TRNFR_INC_CD,FIN_OBJECT_TYP_TRNFR_EXP_CD,NMNL_FIN_BAL_TYP_CD)
  VALUES (2015.0,'fbfa4f25-c126-41e8-93f7-c4ee494c38cd',2.0,'AC','CB','Y',2014.0,'07','IN','EX','EE','ES','AS','LI','FB','EX','IE','PE','TR','IC','CH','IU','2014-2015','N','CE','BB','MB','TI','TE','NB')
/
