--
-- Copyright 2010-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE GL_PENDING_ENTRY_T
/
INSERT INTO GL_PENDING_ENTRY_T (FS_ORIGIN_CD,FDOC_NBR,TRN_ENTR_SEQ_NBR,OBJ_ID,VER_NBR,FIN_COA_CD,ACCOUNT_NBR,SUB_ACCT_NBR,FIN_OBJECT_CD,FIN_SUB_OBJ_CD,FIN_BALANCE_TYP_CD,FIN_OBJ_TYP_CD,UNIV_FISCAL_YR,UNIV_FISCAL_PRD_CD,TRN_LDGR_ENTR_DESC,TRN_LDGR_ENTR_AMT,TRN_DEBIT_CRDT_CD,TRANSACTION_DT,FDOC_TYP_CD,PROJECT_CD,FDOC_REF_TYP_CD,FS_REF_ORIGIN_CD,FDOC_REF_NBR,TRN_ENCUM_UPDT_CD,FDOC_APPROVED_CD,ACCT_SF_FINOBJ_CD,TRN_ENTR_OFST_CD,TRNENTR_PROCESS_TM)
  VALUES ('EP','318788',1.0,'478CB1B9-E39B-E1EF-5D56-6F20A8274A09',2.0,'BL','0212007','-----','4000','---','EX','EX',2009.0,'01','ABC Cleaning Services',995.0,'D',STR_TO_DATE( '20080708000000', '%Y%m%d%H%i%s' ),'OLE_PO','----------','PO','EP','1005','D','N','N/A','N',STR_TO_DATE( '20080708000000', '%Y%m%d%H%i%s' ))
/
INSERT INTO GL_PENDING_ENTRY_T (FS_ORIGIN_CD,FDOC_NBR,TRN_ENTR_SEQ_NBR,OBJ_ID,VER_NBR,FIN_COA_CD,ACCOUNT_NBR,SUB_ACCT_NBR,FIN_OBJECT_CD,FIN_SUB_OBJ_CD,FIN_BALANCE_TYP_CD,FIN_OBJ_TYP_CD,UNIV_FISCAL_YR,UNIV_FISCAL_PRD_CD,TRN_LDGR_ENTR_DESC,TRN_LDGR_ENTR_AMT,TRN_DEBIT_CRDT_CD,TRANSACTION_DT,FDOC_TYP_CD,PROJECT_CD,FDOC_REF_TYP_CD,FS_REF_ORIGIN_CD,FDOC_REF_NBR,TRN_ENCUM_UPDT_CD,FDOC_APPROVED_CD,ACCT_SF_FINOBJ_CD,TRN_ENTR_OFST_CD,TRNENTR_PROCESS_TM)
  VALUES ('EP','318788',2.0,'40F57D38-8E46-B664-E9B2-2BF9E7762623',1.0,'BL','0212007','-----','9892','---','EX','FB',2009.0,'01','TP Generated Offset',995.0,'C',STR_TO_DATE( '20080708000000', '%Y%m%d%H%i%s' ),'OLE_PO','----------','PO','EP','1005','D','N','    ','Y',STR_TO_DATE( '20080708000000', '%Y%m%d%H%i%s' ))
/
