TRUNCATE TABLE OLE_CAT_LOC_COUNTRY_CD_T
/
INSERT INTO OLE_CAT_LOC_COUNTRY_CD_T (LOC_COUNTRY_CD_ID,OBJ_ID,VER_NBR,LOC_COUNTRY_CD,LOC_COUNTRY_NM,LOC_COUNTRY_REGION_NM,LOC_COUNTRY_SEQUENCE_NM,SRC,SRC_DT,ROW_ACT_IND)
  VALUES (1.0,'4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',3.0,'aa','Albania','Europe','Reunion','http://www.loc.gov/marc/countries',STR_TO_DATE( '20120504000000', '%Y%m%d%H%i%s' ),'Y')
/
INSERT INTO OLE_CAT_LOC_COUNTRY_CD_T (LOC_COUNTRY_CD_ID,OBJ_ID,VER_NBR,LOC_COUNTRY_CD,LOC_COUNTRY_NM,LOC_COUNTRY_REGION_NM,LOC_COUNTRY_SEQUENCE_NM,SRC,SRC_DT,ROW_ACT_IND)
  VALUES (2.0,'4dcdf94f-fc19-40f4-86b6-9a3a66d42bda',3.0,'in','India','Asia','Reunion','http://www.loc.gov/marc/countries',STR_TO_DATE( '20120504000000', '%Y%m%d%H%i%s' ),'Y')
/
