--
-- Copyright 2010-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE CA_FEDERAL_FUNC_T DROP STORAGE
/
INSERT INTO CA_FEDERAL_FUNC_T (FIN_FED_FUNC_CD,OBJ_ID,VER_NBR,FIN_FED_FUNC_NM,ROW_ACTV_IND)
  VALUES ('GA','0DF1CCE1765BB5BCE043814FD881B5BC',1.0,'GENERAL ADMINISTRATION','Y')
/
INSERT INTO CA_FEDERAL_FUNC_T (FIN_FED_FUNC_CD,OBJ_ID,VER_NBR,FIN_FED_FUNC_NM,ROW_ACTV_IND)
  VALUES ('IUR','0DF1CCE1765CB5BCE043814FD881B5BC',1.0,'INSTRUCTION AND UNSPONSORED RESEARCH','Y')
/
INSERT INTO CA_FEDERAL_FUNC_T (FIN_FED_FUNC_CD,OBJ_ID,VER_NBR,FIN_FED_FUNC_NM,ROW_ACTV_IND)
  VALUES ('LIB','0DF1CCE1765DB5BCE043814FD881B5BC',1.0,'LIBRARY SERVICES','Y')
/
INSERT INTO CA_FEDERAL_FUNC_T (FIN_FED_FUNC_CD,OBJ_ID,VER_NBR,FIN_FED_FUNC_NM,ROW_ACTV_IND)
  VALUES ('NA','0DF1CCE1765EB5BCE043814FD881B5BC',1.0,'NOT APPLICABLE TO ACCOUNT','Y')
/
INSERT INTO CA_FEDERAL_FUNC_T (FIN_FED_FUNC_CD,OBJ_ID,VER_NBR,FIN_FED_FUNC_NM,ROW_ACTV_IND)
  VALUES ('OIA','0DF1CCE1765FB5BCE043814FD881B5BC',1.0,'OTHER INSTITUTIONAL ACTIVITIES','Y')
/
INSERT INTO CA_FEDERAL_FUNC_T (FIN_FED_FUNC_CD,OBJ_ID,VER_NBR,FIN_FED_FUNC_NM,ROW_ACTV_IND)
  VALUES ('PP','0DF1CCE17660B5BCE043814FD881B5BC',1.0,'PHYSICAL PLANT','Y')
/
INSERT INTO CA_FEDERAL_FUNC_T (FIN_FED_FUNC_CD,OBJ_ID,VER_NBR,FIN_FED_FUNC_NM,ROW_ACTV_IND)
  VALUES ('SA','0DF1CCE17661B5BCE043814FD881B5BC',1.0,'STUDENT AID','Y')
/
INSERT INTO CA_FEDERAL_FUNC_T (FIN_FED_FUNC_CD,OBJ_ID,VER_NBR,FIN_FED_FUNC_NM,ROW_ACTV_IND)
  VALUES ('SAS','0DF1CCE17662B5BCE043814FD881B5BC',1.0,'STUDENT ADMINISTRATION AND SERVICES','Y')
/
INSERT INTO CA_FEDERAL_FUNC_T (FIN_FED_FUNC_CD,OBJ_ID,VER_NBR,FIN_FED_FUNC_NM,ROW_ACTV_IND)
  VALUES ('SPA','0DF1CCE17663B5BCE043814FD881B5BC',1.0,'SPONSORED PROGRAM ADMIN.','Y')
/
INSERT INTO CA_FEDERAL_FUNC_T (FIN_FED_FUNC_CD,OBJ_ID,VER_NBR,FIN_FED_FUNC_NM,ROW_ACTV_IND)
  VALUES ('SPS','0DF1CCE17664B5BCE043814FD881B5BC',1.0,'SPONSORED PUBLIC SERVICE','Y')
/
INSERT INTO CA_FEDERAL_FUNC_T (FIN_FED_FUNC_CD,OBJ_ID,VER_NBR,FIN_FED_FUNC_NM,ROW_ACTV_IND)
  VALUES ('SR','0DF1CCE17665B5BCE043814FD881B5BC',1.0,'SPONSORED RESEARCH','Y')
/
