--
-- Copyright 2010-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE CA_OBJ_CONSOLDTN_T DROP STORAGE
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','ASEX','014F3DAF7384A448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','ASRE','014F3DAF7385A448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','ASST','014F3DAF7386A448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','CMPN','014F3DAF7387A448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','CPTL','014F3DAF7388A448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','FDBL','014F3DAF7389A448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','GENX','014F3DAF738AA448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','IDEX','014F3DAF738BA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','IDIN','014F3DAF738CA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','LIAB','014F3DAF738DA448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','OTRE','014F3DAF738EA448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','RSRX','014F3DAF738FA448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','SAPR','014F3DAF7390A448E043814FD28EA448',1.0,'STATE APPROPRIATION','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','SCHL','014F3DAF7391A448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','STFE','014F3DAF7392A448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','TFEX','014F3DAF7393A448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','TFIN','014F3DAF7394A448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','TRSF','014F3DAF7395A448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BA','TRVL','014F3DAF7396A448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','ASEX','014F3DAF7397A448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','ASRE','014F3DAF7398A448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','ASST','014F3DAF7399A448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','CMPN','014F3DAF739AA448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','CPTL','014F3DAF739BA448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','FDBL','014F3DAF739CA448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','GENX','014F3DAF739DA448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','IDEX','014F3DAF739EA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','IDIN','014F3DAF739FA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','LIAB','014F3DAF73A0A448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','MONO','BL-MONO',1.0,'Monographic Purchases','Mono','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','OTRE','014F3DAF73A1A448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','RSRX','014F3DAF73A2A448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','SAPR','014F3DAF73A3A448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','SCHL','014F3DAF73A4A448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','SERL','BL-SERL',1.0,'Serial Purchases','Serial','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','STFE','014F3DAF73A5A448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','TFEX','014F3DAF73A6A448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','TFIN','014F3DAF73A7A448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','TRSF','014F3DAF73A8A448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('BL','TRVL','014F3DAF73A9A448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','ASEX','014F3DAF73AAA448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','ASRE','014F3DAF73ABA448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','ASST','014F3DAF73ACA448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','CMPN','014F3DAF73ADA448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','CPTL','014F3DAF73AEA448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','FDBL','014F3DAF73AFA448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','GENX','014F3DAF73B0A448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','IDEX','014F3DAF73B1A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','IDIN','014F3DAF73B2A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','LIAB','014F3DAF73B3A448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','OTRE','014F3DAF73B4A448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','RSRX','014F3DAF73B5A448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','SAPR','014F3DAF73B6A448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','SCHL','014F3DAF73B7A448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','STFE','014F3DAF73B8A448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','TFEX','014F3DAF73B9A448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','TFIN','014F3DAF73BAA448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','TRSF','014F3DAF73BBA448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('EA','TRVL','014F3DAF73BCA448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','ASEX','014F3DAF73BDA448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','ASRE','014F3DAF73BEA448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','ASST','014F3DAF73BFA448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','CMPN','014F3DAF73C0A448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','CPTL','014F3DAF73C1A448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','FDBL','014F3DAF73C2A448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','GENX','014F3DAF73C3A448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','IDEX','014F3DAF73C4A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','IDIN','014F3DAF73C5A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','LIAB','014F3DAF73C6A448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','OTRE','014F3DAF73C7A448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','RSRX','014F3DAF73C8A448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','SAPR','014F3DAF73C9A448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','SCHL','014F3DAF73CAA448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','STFE','014F3DAF73CBA448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','TFEX','014F3DAF73CCA448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','TFIN','014F3DAF73CDA448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','TRSF','014F3DAF73CEA448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('FW','TRVL','014F3DAF73CFA448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','ASEX','014F3DAF73D0A448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','ASRE','014F3DAF73D1A448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','ASST','014F3DAF73D2A448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','CMPN','014F3DAF73D3A448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','CPTL','014F3DAF73D4A448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','FDBL','014F3DAF73D5A448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','GENX','014F3DAF73D6A448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','IDEX','014F3DAF73D7A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','IDIN','014F3DAF73D8A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','LIAB','014F3DAF73D9A448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','OTRE','014F3DAF73DAA448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','RSRX','014F3DAF73DBA448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','SAPR','014F3DAF73DCA448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','SCHL','014F3DAF73DDA448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','STFE','014F3DAF73DEA448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','TFEX','014F3DAF73DFA448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','TFIN','014F3DAF73E0A448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','TRSF','014F3DAF73E1A448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('HO','TRVL','014F3DAF73E2A448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','ASEX','014F3DAF73E3A448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','ASRE','014F3DAF73E4A448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','ASST','014F3DAF73E5A448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','CMPN','014F3DAF73E6A448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','CPTL','014F3DAF73E7A448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','FDBL','014F3DAF73E8A448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','GENX','014F3DAF73E9A448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','IDEX','014F3DAF73EAA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','IDIN','014F3DAF73EBA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','LIAB','014F3DAF73ECA448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','OTRE','014F3DAF73EDA448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','RSRX','014F3DAF73EEA448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','SAPR','014F3DAF73EFA448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','SCHL','014F3DAF73F0A448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','STFE','014F3DAF73F1A448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','TFEX','014F3DAF73F2A448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','TFIN','014F3DAF73F3A448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','TRSF','014F3DAF73F4A448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IA','TRVL','014F3DAF73F5A448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','ASEX','014F3DAF73F6A448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','ASRE','014F3DAF73F7A448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','ASST','014F3DAF73F8A448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','CMPN','014F3DAF73F9A448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','CPTL','014F3DAF73FAA448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','FDBL','014F3DAF73FBA448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','GENX','014F3DAF73FCA448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','IDEX','014F3DAF73FDA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','IDIN','014F3DAF73FEA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','LIAB','014F3DAF73FFA448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','OTRE','014F3DAF7400A448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','RSRX','014F3DAF7401A448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','SAPR','014F3DAF7402A448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','SCHL','014F3DAF7403A448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','STFE','014F3DAF7404A448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','TFEX','014F3DAF7405A448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','TFIN','014F3DAF7406A448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','TRSF','014F3DAF7407A448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IN','TRVL','014F3DAF7408A448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','ASEX','014F3DAF7409A448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','ASRE','014F3DAF740AA448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','ASST','014F3DAF740BA448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','AUXE','014F3DAF747BA448E043814FD28EA448',1.0,'AUXILIARY ENTERPRISES','AUX ENT','N','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','CMPN','014F3DAF740CA448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','CPTL','014F3DAF740DA448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','FDBL','014F3DAF740EA448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','GENX','014F3DAF740FA448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','IDEX','014F3DAF7410A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','IDIN','014F3DAF7411A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','LIAB','014F3DAF7412A448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','MONO','IU-MONO',1.0,'Monographic Purchases','Mono','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','OTRE','014F3DAF7413A448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','RSRX','014F3DAF7414A448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','SAPR','014F3DAF7415A448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','SCHL','014F3DAF7416A448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','SERL','IU-SERL',1.0,'Serial Purchases','Serial','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','STFE','014F3DAF7417A448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','TFEX','014F3DAF7418A448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','TFIN','014F3DAF7419A448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','TRSF','014F3DAF741AA448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('IU','TRVL','014F3DAF741BA448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','ASEX','014F3DAF741CA448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','ASRE','014F3DAF741DA448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','ASST','014F3DAF741EA448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','CMPN','014F3DAF741FA448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','CPTL','014F3DAF7420A448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','FDBL','014F3DAF7421A448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','GENX','014F3DAF7422A448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','IDEX','014F3DAF7423A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','IDIN','014F3DAF7424A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','LIAB','014F3DAF7425A448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','OTRE','014F3DAF7426A448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','RSRX','014F3DAF7427A448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','SAPR','014F3DAF7428A448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','SCHL','014F3DAF7429A448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','STFE','014F3DAF742AA448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','TFEX','014F3DAF742BA448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','TFIN','014F3DAF742CA448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','TRSF','014F3DAF742DA448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('KO','TRVL','014F3DAF742EA448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','ASEX','014F3DAF742FA448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','ASRE','014F3DAF7430A448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','ASST','014F3DAF7431A448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','CMPN','014F3DAF7432A448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','CPTL','014F3DAF7433A448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','FDBL','014F3DAF7434A448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','GENX','014F3DAF7435A448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','IDEX','014F3DAF7436A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','IDIN','014F3DAF7437A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','LIAB','014F3DAF7438A448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','OTRE','014F3DAF7439A448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','RSRX','014F3DAF743AA448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','SAPR','014F3DAF743BA448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','SCHL','014F3DAF743CA448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','STFE','014F3DAF743DA448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','TFEX','014F3DAF743EA448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','TFIN','014F3DAF743FA448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','TRSF','014F3DAF7440A448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('NW','TRVL','014F3DAF7441A448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','ASEX','014F3DAF7442A448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','ASRE','014F3DAF7443A448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','ASST','014F3DAF7444A448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','CMPN','014F3DAF7445A448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','CPTL','014F3DAF7446A448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','FDBL','014F3DAF7447A448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','GENX','014F3DAF7448A448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','IDEX','014F3DAF7449A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','IDIN','014F3DAF744AA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','LIAB','014F3DAF744BA448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','OTRE','014F3DAF744CA448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','RSRX','014F3DAF744DA448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','SAPR','014F3DAF744EA448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','SCHL','014F3DAF744FA448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','STFE','014F3DAF7450A448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','TFEX','014F3DAF7451A448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','TFIN','014F3DAF7452A448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','TRSF','014F3DAF7453A448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SB','TRVL','014F3DAF7454A448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','ASEX','014F3DAF7455A448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','ASRE','014F3DAF7456A448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','ASST','014F3DAF7457A448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','CMPN','014F3DAF7458A448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','CPTL','014F3DAF7459A448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','FDBL','014F3DAF745AA448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','GENX','014F3DAF745BA448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','IDEX','014F3DAF745CA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','IDIN','014F3DAF745DA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','LIAB','014F3DAF745EA448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','OTRE','014F3DAF745FA448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','RSRX','014F3DAF7460A448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','SAPR','014F3DAF7461A448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','SCHL','014F3DAF7462A448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','STFE','014F3DAF7463A448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','TFEX','014F3DAF7464A448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','TFIN','014F3DAF7465A448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','TRSF','014F3DAF7466A448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('SE','TRVL','014F3DAF7467A448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','ASEX','014F3DAF7468A448E043814FD28EA448',1.0,'ASSESSMENTS-EXPENDITURES','ASSESS-EXP','Y','13')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','ASRE','014F3DAF7469A448E043814FD28EA448',1.0,'ASSESSMENTS-REVENUE','ASSESS-REV','Y','05')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','ASST','014F3DAF746AA448E043814FD28EA448',1.0,'ASSETS','ASSETS','Y','16')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','CMPN','014F3DAF746BA448E043814FD28EA448',1.0,'COMPENSATION','COMPENS','Y','07')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','CPTL','014F3DAF746CA448E043814FD28EA448',1.0,'CAPITAL','CAPITAL','Y','11')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','FDBL','014F3DAF746DA448E043814FD28EA448',1.0,'FUND BALANCE','FUND BAL','Y','18')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','GENX','014F3DAF746EA448E043814FD28EA448',1.0,'GENERAL EXPENSE','GEN EXP','Y','09')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','IDEX','014F3DAF746FA448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY EXPENSE','IND COST EXP','Y','12')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','IDIN','014F3DAF7470A448E043814FD28EA448',1.0,'INDIRECT COST RECOVERY INCOME','IND COST INC','Y','04')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','LIAB','014F3DAF7471A448E043814FD28EA448',1.0,'LIABILITIES','LIABILITIES','Y','17')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','OTRE','014F3DAF7472A448E043814FD28EA448',1.0,'OTHER REVENUE','OTH REVENUE','Y','03')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','RSRX','014F3DAF7473A448E043814FD28EA448',1.0,'RESERVES','RESERVES','Y','15')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','SAPR','014F3DAF7474A448E043814FD28EA448',1.0,'STATE APPROPRIATIONS','STATE APPROP','Y','02')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','SCHL','014F3DAF7475A448E043814FD28EA448',1.0,'FINANCIAL AID','FIN AID','Y','08')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','STFE','014F3DAF7476A448E043814FD28EA448',1.0,'STUDENT FEES','STUDENT FEES','Y','01')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','TFEX','014F3DAF7477A448E043814FD28EA448',1.0,'TRANSFER - EXPENSE','TRANSFER-EXP','N','14')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','TFIN','014F3DAF7478A448E043814FD28EA448',1.0,'TRANSFER - INCOME','TRANSFER-INC','N','06')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','TRSF','014F3DAF7479A448E043814FD28EA448',1.0,'TRANSFER OF FUNDS','TRANSFER','Y','19')
/
INSERT INTO CA_OBJ_CONSOLDTN_T (FIN_COA_CD,FIN_CONS_OBJ_CD,OBJ_ID,VER_NBR,FIN_CONS_OBJ_NM,FIN_CONOBJ_SHRT_NM,FIN_CONOBJ_ACTV_CD,FIN_REPORT_SORT_CD)
  VALUES ('UA','TRVL','014F3DAF747AA448E043814FD28EA448',1.0,'TRAVEL','TRAVEL','Y','10')
/
