--
-- Copyright 2010-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE CG_AGENCY_T DROP STORAGE
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('11500','0292B100447EBBDEE043814FD881BBDE',1.0,'US DEPT OF DEFENSE','U.S. DEPARTMENT OF DEFENSE',0.0,'N','N','F')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('11505','0292B100447FBBDEE043814FD881BBDE',1.0,'US AIR FORCE','U.S. AIR FORCE',0.0,'N','N','F','11500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('11510','0292B1004480BBDEE043814FD881BBDE',1.0,'UNITED STATES ARMY','U.S. ARMY',0.0,'N','N','F','11500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('11555','0292B1004481BBDEE043814FD881BBDE',1.0,'US NAVY','U.S. NAVY',0.0,'N','N','F','11500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('12010','0292B1004482BBDEE043814FD881BBDE',1.0,'US DHHS','U.S. DEPARTMENT OF HEALTH AND HUMAN SERVICES',0.0,'N','N','F')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('12100','0292B1004483BBDEE043814FD881BBDE',1.0,'US OFFICE OF EDUC','U.S. OFFICE OF EDUCATION',0.0,'Y','N','F')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('12110','0292B1004484BBDEE043814FD881BBDE',1.0,'US DEPT OF EDUCATION','U.S. DEPARTMENT OF EDUCATION',0.0,'N','N','F')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12500','0292B1004485BBDEE043814FD881BBDE',1.0,'NIH','NATIONAL INSTITUTES OF HEALTH',0.0,'N','N','F','12010')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12550','0292B1004486BBDEE043814FD881BBDE',1.0,'NIH CONTRACT','NATIONAL INSTITUTES OF HEALTH CONTRACT',0.0,'Y','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12601','0292B1004487BBDEE043814FD881BBDE',1.0,'NIH-NIA','NATIONAL INSTITUTE ON AGING',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12602','0292B1004488BBDEE043814FD881BBDE',1.0,'NATL INST ALLIED HLTH','NATIONAL INSTITUTE OF ALLIED HEALTH',0.0,'Y','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12610','0292B1004489BBDEE043814FD881BBDE',1.0,'NIH-NCI','NATIONAL CANCER INSTITUTE',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12615','0292B100448ABBDEE043814FD881BBDE',1.0,'NIH-NIDCD','NATIONAL INSTITUTE ON DEAFNESS AND OTHER COMM. DIS',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12624','0292B100448BBBDEE043814FD881BBDE',1.0,'NIH-NEI','NATIONAL EYE INSTITUTE',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12631','0292B100448CBBDEE043814FD881BBDE',1.0,'NIH-NIGMS','NATIONAL INSTITUTE OF GENERAL MEDICAL SCIENCES',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12636','0292B100448DBBDEE043814FD881BBDE',1.0,'NIH-NICHD','NATIONAL INSTITUTE OF CHILD HEALTH, HUMAN DEVL.',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12637','0292B100448EBBDEE043814FD881BBDE',1.0,'NIH-NHLBI','NATIONAL HEART, LUNG AND BLOOD INSTITUTE',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('12651','0292B100448FBBDEE043814FD881BBDE',1.0,'HEALTH MANPOWER EDU','HEALTH MANPOWER EDUCATION',0.0,'N','N','F')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12658','0292B1004490BBDEE043814FD881BBDE',1.0,'NIH-NINDS','NATIONAL INST OF NEUROLOGICAL DISORDERS & STROKE',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12673','0292B1004491BBDEE043814FD881BBDE',1.0,'DEPT RESEARCH RES','DEPARTMENT OF RESEARCH RESOURCES',0.0,'Y','N','F','12010')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12683','0292B1004492BBDEE043814FD881BBDE',1.0,'NIH-FOGARTY INTL CTR','FOGARTY INTERNATIONAL CENTER',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12815','0292B1004493BBDEE043814FD881BBDE',1.0,'CDC','CENTERS FOR DISEASE CONTROL & PREVENTION',0.0,'N','N','F','12010')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12851','0292B1004494BBDEE043814FD881BBDE',1.0,'NIH-NIMH','NATIONAL INSTITUTE OF MENTAL HEALTH',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12852','0292B1004495BBDEE043814FD881BBDE',1.0,'NIH-NIAAA','NATIONAL INSTITUTE ON ALCOHOL ABUSE & ALCOHOLISM',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('12853','0292B1004496BBDEE043814FD881BBDE',1.0,'NIH-NIDA','NATIONAL INSTITUTE ON DRUG ABUSE',0.0,'N','N','F','12500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('18500','0292B1004497BBDEE043814FD881BBDE',1.0,'NATIONAL SCIENCE FDN','NATIONAL SCIENCE FOUNDATION',0.0,'N','N','F')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('19000','0292B1004498BBDEE043814FD881BBDE',1.0,'MISC UNITED STATES AGENCIES','MISCELLANEOUS UNITED STATES AGENCIES',0.0,'Y','N','F')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('19150','0292B1004499BBDEE043814FD881BBDE',1.0,'US DEPT OF ENERGY','U.S. DEPARTMENT OF ENERGY',0.0,'N','N','F')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('19275','0292B100449ABBDEE043814FD881BBDE',1.0,'US EPA','U.S. ENVIRONMENTAL PROTECTION AGENCY',0.0,'N','N','F')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('19500','0292B100449BBBDEE043814FD881BBDE',1.0,'NASA','NATIONAL AERONAUTICS AND SPACE ADMINISTRATION',0.0,'N','N','F')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20200','0292B100449CBBDEE043814FD881BBDE',1.0,'EASTER SEAL FDN','EASTER SEAL FOUNDATION',0.0,'Y','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20225','0292B100449DBBDEE043814FD881BBDE',1.0,'EXXON EDU FDN','EXXON EDUCATION FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20280','0292B100449EBBDEE043814FD881BBDE',1.0,'THE FORD FOUNDATION','THE FORD FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20325','0292B100449FBBDEE043814FD881BBDE',1.0,'WILLIAM T GRANT FDN','WILLIAM T. GRANT FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20337','0292B10044A0BBDEE043814FD881BBDE',1.0,'JOHN SIMON GUGGENHEIM MEM.FDN.','JOHN SIMON GUGGENHEIM MEMORIAL FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20456','0292B10044A1BBDEE043814FD881BBDE',1.0,'LILLY ENDOWMENT','LILLY ENDOWMENT, INCORPORATED',0.0,'N','Y','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20535','0292B10044A2BBDEE043814FD881BBDE',1.0,'MISCELLANEOUS FOUNDATIONS','MISCELLANEOUS FOUNDATIONS',0.0,'Y','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20557','0292B10044A3BBDEE043814FD881BBDE',1.0,'CYSTIC FIBROSIS FDN','CYSTIC FIBROSIS FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20565','0292B10044A4BBDEE043814FD881BBDE',1.0,'MOD BIRTH DEFECTS FOUNDATION','MARCH OF DIMES BIRTH DEFECTS FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20770','0292B10044A5BBDEE043814FD881BBDE',1.0,'ALFRED P SLOAN FDN','ALFRED P. SLOAN FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20780','0292B10044A6BBDEE043814FD881BBDE',1.0,'SPENCER FDN','THE SPENCER FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('20927','0292B10044A7BBDEE043814FD881BBDE',1.0,'WHITEHALL FDN INC','WHITEHALL FOUNDATION, INC.',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30026','0292B10044A8BBDEE043814FD881BBDE',1.0,'AM PHILOSOPHICAL SOC','AMERICAN PHILOSOPHICAL SOCIETY',0.0,'N','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30042','0292B10044A9BBDEE043814FD881BBDE',1.0,'ASSN ADV MENTAL HLTH','ASSOCIATION FOR ADVANCEMENT OF MENTAL HEALTH RESEA',0.0,'N','Y','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30105','0292B10044AABBDEE043814FD881BBDE',1.0,'UNIV OF CALIFORNIA','REGENTS OF THE UNIVERSITY OF CALIFORNIA',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30109','0292B10044ABBBDEE043814FD881BBDE',1.0,'CTR ADV STUDY BEH SC','CENTER FOR ADVANCED STUDY OF BEHAVIORAL SCIENCE',0.0,'N','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30155','0292B10044ACBBDEE043814FD881BBDE',1.0,'DARTMOUTH COLLEGE','DARTMOUTH COLLEGE',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30420','0292B10044ADBBDEE043814FD881BBDE',1.0,'AM HEART-IND AFFIL','AMERICAN HEART ASSOCIATION, INDIANA AFFILIATE, INC',0.0,'Y','Y','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30493','0292B10044AEBBDEE043814FD881BBDE',1.0,'MISCELLANEOUS NON PROFIT','MISCELLANEOUS NON PROFIT',0.0,'Y','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30505','0292B10044AFBBDEE043814FD881BBDE',1.0,'MIDWEST UNIV CONSORT INTL ACT','MIDWEST UNIVERSITIES CONSORTIUM FOR INTL ACT, INC',0.0,'N','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30680','0292B10044B0BBDEE043814FD881BBDE',1.0,'PURDUE UNIVERSITY','PURDUE UNIVERSITY',0.0,'N','Y','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30801','0292B10044B1BBDEE043814FD881BBDE',1.0,'SCOTTISH RITE INDPLS','SCOTTISH RITE VALLEY OF INDIANAPOLIS',0.0,'N','Y','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30871','0292B10044B2BBDEE043814FD881BBDE',1.0,'UNIV OF ILLINOIS','UNIVERSITY  OF ILLINOIS',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('30977','0292B10044B3BBDEE043814FD881BBDE',1.0,'UNIV OF WISCONSIN','UNIVERSITY OF WISCONSIN',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('40100','0292B10044B4BBDEE043814FD881BBDE',1.0,'STATE OF INDIANA','STATE OF INDIANA',0.0,'N','Y','S')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('40170','0292B10044B5BBDEE043814FD881BBDE',1.0,'IND DEPT EDUCATION','INDIANA DEPARTMENT OF EDUCATION',0.0,'N','Y','S','40100')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('40200','0292B10044B6BBDEE043814FD881BBDE',1.0,'IFSSA-MENTAL HEALTH','INDIANA DIV OF MENTAL HEALTH & ADDICTION',0.0,'N','Y','S')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('40700','0292B10044B7BBDEE043814FD881BBDE',1.0,'SCHOOL CORPORATION','SCHOOL CORPORATION',0.0,'Y','Y','G')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('50370','0292B10044B8BBDEE043814FD881BBDE',1.0,'HOFFMANN LA ROCHE','HOFFMANN LA ROCHE INCORPORATED',0.0,'N','N','I')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('50402','0292B10044B9BBDEE043814FD881BBDE',1.0,'IBM','INTERNATIONAL BUSINESS MACHINES',0.0,'N','N','I')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('50530','0292B10044BABBDEE043814FD881BBDE',1.0,'MISCELLANEOUS INDUSTRY-COMM','MISCELLANEOUS INDUSTRY-COMM',0.0,'Y','N','I')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('50757','0292B10044BBBBDEE043814FD881BBDE',1.0,'SCHERING CORP','SCHERING CORPORATION',0.0,'N','N','I')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('50971','0292B10044BCBBDEE043814FD881BBDE',1.0,'HEREDITARY DIS FDN','THE HEREDITARY DISEASE FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51200','0292B10044BDBBDEE043814FD881BBDE',1.0,'AUBURN UNIVERSITY','AUBURN UNIVERSITY',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51215','0292B10044BEBBDEE043814FD881BBDE',1.0,'BROWN UNIVERSITY','BROWN UNIVERSITY',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51261','0292B10044BFBBDEE043814FD881BBDE',1.0,'DUKE UNIVERSITY','DUKE UNIVERSITY',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51280','0292B10044C0BBDEE043814FD881BBDE',1.0,'GALLAUDET UNIVERSITY','GALLAUDET UNIVERSITY',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51305','0292B10044C1BBDEE043814FD881BBDE',1.0,'HOWARD HUGHES MED','HOWARD HUGHES MEDICAL INSTITUTE',0.0,'N','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51490','0292B10044C2BBDEE043814FD881BBDE',1.0,'ALCOH BEV MED RES','ALCOHOLIC BEVERAGE MEDICAL RESEARCH FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51608','0292B10044C3BBDEE043814FD881BBDE',1.0,'SOUTHEASTERN CENTER ELECT ENG','SOUTHEASTERN CENTER ELECT ENG',0.0,'N','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('51651','0292B10044C4BBDEE043814FD881BBDE',1.0,'UNIV CALIF SB','UNIVERSITY OF CALIFORNIA, SANTA BARBARA',0.0,'N','N','H','30105')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51657','0292B10044C5BBDEE043814FD881BBDE',1.0,'UNIV OF GEORGIA','UNIVERSITY OF GEORGIA',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51665','0292B10044C6BBDEE043814FD881BBDE',1.0,'UNIV OF MINNESOTA','UNIVERSITY OF MINNESOTA',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51674','0292B10044C7BBDEE043814FD881BBDE',1.0,'UNIV OF TENNESSEE','UNIVERSITY OF TENNESSEE',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51922','0292B10044C8BBDEE043814FD881BBDE',1.0,'UNIV KY RESEARCH FDN','UNIVERSITY OF KENTUCKY RESEARCH FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51944','0292B10044C9BBDEE043814FD881BBDE',1.0,'UNIV SOUTHERN CALIF','UNIVERSITY OF SOUTHERN CALIFORNIA',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('51950','0292B10044CABBDEE043814FD881BBDE',1.0,'AM SPCH-LANG-HRNG FD','AMERICAN SPEECH-LANUGAGE-HEARING FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('51954','0292B10044CBBBDEE043814FD881BBDE',1.0,'UNIV ILLINOIS URBANA','UNIVERSITY OF ILLINOIS AT URBANA-CHAMPAIGN',0.0,'N','N','H','30871')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('52034','0292B10044CCBBDEE043814FD881BBDE',1.0,'ILLINOIS STATE UNIV.','ILLINOIS STATE UNIVERSITY',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('52084','0292B10044CDBBDEE043814FD881BBDE',1.0,'NARSAD','NATIONAL ALLIANCE FOR RES ON SCHIZOPHRENIA',0.0,'N','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('52217','0292B10044CEBBDEE043814FD881BBDE',1.0,'UNIV OF DELAWARE','UNIVERSITY OF DELAWARE',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('52256','0292B10044CFBBDEE043814FD881BBDE',1.0,'CEPHALON INC','CEPHALON, INC.',0.0,'N','N','I')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('52341','0292B10044D0BBDEE043814FD881BBDE',1.0,'UNIVERSITY OF IOWA','UNIVERSITY OF IOWA',0.0,'N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('52391','0292B10044D1BBDEE043814FD881BBDE',1.0,'A & M BECKMAN FDN','ARNOLD AND MABEL BECKMAN FOUNDATION',0.0,'N','N','D')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGNCY_INDR_AMT,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('52419','0292B10044D2BBDEE043814FD881BBDE',1.0,'SMITH & WESSON','SMITH & WESSON',0.0,'N','N','I')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('52590','0292B10044D3BBDEE043814FD881BBDE',1.0,'ADMIN CHILDREN & FAM','ADMINISTRATION FOR CHILDREN AND FAMILIES','N','N','F','12010')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('52604','0292B10044D4BBDEE043814FD881BBDE',1.0,'CHILDRENS HOS-CIN','CHILDREN''S HOSPITAL MEDICAL CENTER OF CINCINNATI','N','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('52631','0292B10044D5BBDEE043814FD881BBDE',1.0,'SPATIAL MEDIA, INC.','SPATIAL MEDIA, INC.','N','N','I')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('52846','0292B10044D6BBDEE043814FD881BBDE',1.0,'HOUSE EAR INST','HOUSE EAR INSTITUTE','N','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('52926','0292B10044D7BBDEE043814FD881BBDE',1.0,'RHODE ISLAND HOSPITAL','RHODE ISLAND HOSPITAL','Y','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('53024','0292B10044D8BBDEE043814FD881BBDE',1.0,'OLFACTORY RES FUND','OLFACTORY RESEARCH FUND LTD','N','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('53143','0292B10044D9BBDEE043814FD881BBDE',1.0,'ANIMAL BEHAVIOR SOCIETY','ANIMAL BEHAVIOR SOCIETY','N','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('53419','0292B10044DABBDEE043814FD881BBDE',1.0,'STAR ENTERPRISES INC','STAR ENTERPRISES INC','N','Y','I')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('53429','0292B10044DBBBDEE043814FD881BBDE',1.0,'UNIV FLORIDA','UNIVERSITY OF FLORIDA','N','N','H')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('53567','0292B10044DCBBDEE043814FD881BBDE',1.0,'LOCKHEED MARTIN ENGY RES CORP','LOCKHEED MARTIN ENERGY RESEARCH CORP','N','N','I')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('53745','0292B10044DDBBDEE043814FD881BBDE',1.0,'AVENTIS PHARMACEUTICAL','AVENTIS PHARMACEUTICAL PRODUCTS, INC.','N','N','I')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('53960','0292B10044DEBBDEE043814FD881BBDE',1.0,'NATL IMAGERY & MAPPING AGENCY','NATIONAL IMAGERY AND MAPPING AGENCY','Y','N','F','11500')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('54017','0292B10044DFBBDEE043814FD881BBDE',1.0,'SCRIPPS RESEARCH INSTITUTE','SCRIPPS RESEARCH INSTITUTE','N','N','P')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('54031','0292B10044E0BBDEE043814FD881BBDE',1.0,'SWEDISH NATL DEFENCE COLL','SWEDISH NATIONAL DEFENCE COLLEGE','N','N','G')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD)
  VALUES ('54040','0292B10044E1BBDEE043814FD881BBDE',1.0,'PSYCHOLOGICAL ASSESS','PSYCHOLOGICAL ASSESSMENT RESOURCES INC','N','N','I')
/
INSERT INTO CG_AGENCY_T (CG_AGENCY_NBR,OBJ_ID,VER_NBR,CG_AGENCY_RPT_NM,CG_AGENCY_FULL_NM,CG_AGENCY_HIST_IND,CG_AGNCY_IN_ST_IND,CG_AGENCY_TYP_CD,CG_RPTTO_AGNCY_NBR)
  VALUES ('54643','0292B10044E2BBDEE043814FD881BBDE',1.0,'DOD-NATL GEOINT AGENCY','NATIONAL GEOSPATIAL-INTELLIGENCE AGENCY','N','N','F','11500')
/
