--
-- Copyright 2010-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE FS_TAX_COUNTY_T DROP STORAGE
/
INSERT INTO FS_TAX_COUNTY_T (POSTAL_CNTRY_CD,COUNTY_CD,STATE_CD,TAX_REGION_CD,OBJ_ID,VER_NBR,ACTV_IND)
  VALUES ('US','13','AZ','12','5ACF22CFC6174AB0E0404F8189D87AB9',1.0,'Y')
/
INSERT INTO FS_TAX_COUNTY_T (POSTAL_CNTRY_CD,COUNTY_CD,STATE_CD,TAX_REGION_CD,OBJ_ID,VER_NBR,ACTV_IND)
  VALUES ('US','19','AZ','05PERCNTY','5ACF22CFC6154AB0E0404F8189D87AB9',1.0,'Y')
/
INSERT INTO FS_TAX_COUNTY_T (POSTAL_CNTRY_CD,COUNTY_CD,STATE_CD,TAX_REGION_CD,OBJ_ID,VER_NBR,ACTV_IND)
  VALUES ('US','37','CA','4','5ACF22CFC6144AB0E0404F8189D87AB9',1.0,'Y')
/
INSERT INTO FS_TAX_COUNTY_T (POSTAL_CNTRY_CD,COUNTY_CD,STATE_CD,TAX_REGION_CD,OBJ_ID,VER_NBR,ACTV_IND)
  VALUES ('US','5','AZ','9','5ACF22CFC6164AB0E0404F8189D87AB9',1.0,'Y')
/
INSERT INTO FS_TAX_COUNTY_T (POSTAL_CNTRY_CD,COUNTY_CD,STATE_CD,TAX_REGION_CD,OBJ_ID,VER_NBR,ACTV_IND)
  VALUES ('US','65','CA','05PERCNTY','6B64AB2CF60B9938E0404F8189D824B6',1.0,'Y')
/
INSERT INTO FS_TAX_COUNTY_T (POSTAL_CNTRY_CD,COUNTY_CD,STATE_CD,TAX_REGION_CD,OBJ_ID,VER_NBR,ACTV_IND)
  VALUES ('US','71','CA','05PERCNTY','6B64AB2CF60D9938E0404F8189D824B6',1.0,'Y')
/
INSERT INTO FS_TAX_COUNTY_T (POSTAL_CNTRY_CD,COUNTY_CD,STATE_CD,TAX_REGION_CD,OBJ_ID,VER_NBR,ACTV_IND)
  VALUES ('US','83','CA','05PERCNTY','6B64AB2CF60C9938E0404F8189D824B6',1.0,'Y')
/
