TRUNCATE TABLE OLE_PUR_REQ_RCPT_STATUS_T DROP STORAGE
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (1.0,'Partially Received',1.0,'1','Y')
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (2.0,'Fully Received',1.0,'2','Y')
/
INSERT INTO OLE_PUR_REQ_RCPT_STATUS_T (OLE_REQ_RCPT_STATUS_ID,OLE_REQ_RCPT_STATUS_NM,VER_NBR,OBJ_ID,ROW_ACT_IND)
  VALUES (3.0,'NOT Received',1.0,'3','Y')
/
