TRUNCATE TABLE OLE_VNDR_TRANS_FRMT_TYP_INT_T DROP STORAGE
/
INSERT INTO OLE_VNDR_TRANS_FRMT_TYP_INT_T (VNDR_DTL_ASND_ID,VNDR_HDR_GNRTD_ID,OLE_VNDR_TRANS_FRMT_ID,OLE_PRF_TRANS_FRMT_TYP,OLE_TRANS_TYP_ADD,OLE_TRANS_USR_NM,OLE_TRANS_PW,VER_NBR,OBJ_ID,ROW_ACT_IND,OLE_TRANS_TYP_ID)
  VALUES (0.0,1000.0,1.0,'Y','docstore.dev.ole.kuali.org','upload','data4OLE',1.0,'31183A70-A6AD-02AE-6AA5-3B0242615112','Y',2.0)
/
INSERT INTO OLE_VNDR_TRANS_FRMT_TYP_INT_T (VNDR_DTL_ASND_ID,VNDR_HDR_GNRTD_ID,OLE_VNDR_TRANS_FRMT_ID,OLE_PRF_TRANS_FRMT_TYP,OLE_TRANS_TYP_ADD,OLE_TRANS_USR_NM,OLE_TRANS_PW,VER_NBR,OBJ_ID,ROW_ACT_IND,OLE_TRANS_TYP_ID)
  VALUES (0.0,1009.0,1.0,'Y','docstore.dev.ole.kuali.org','upload','data4ole',2.0,'6903C946-9ECF-D72D-1308-A3AB1D136ECF','Y',2.0)
/
INSERT INTO OLE_VNDR_TRANS_FRMT_TYP_INT_T (VNDR_DTL_ASND_ID,VNDR_HDR_GNRTD_ID,OLE_VNDR_TRANS_FRMT_ID,OLE_PRF_TRANS_FRMT_TYP,OLE_TRANS_TYP_ADD,OLE_TRANS_USR_NM,OLE_TRANS_PW,VER_NBR,OBJ_ID,ROW_ACT_IND,OLE_TRANS_TYP_ID)
  VALUES (0.0,12106.0,1.0,'Y','docstore.dev.ole.kuali.org','upload','data4OLE',1.0,'742A71D9-C15D-B770-A48C-14AD72C4C6E2','Y',2.0)
/
INSERT INTO OLE_VNDR_TRANS_FRMT_TYP_INT_T (VNDR_DTL_ASND_ID,VNDR_HDR_GNRTD_ID,OLE_VNDR_TRANS_FRMT_ID,OLE_PRF_TRANS_FRMT_TYP,OLE_TRANS_TYP_ADD,OLE_TRANS_USR_NM,OLE_TRANS_PW,VER_NBR,OBJ_ID,ROW_ACT_IND,OLE_TRANS_TYP_ID)
  VALUES (0.0,12111.0,1.0,'Y','docstore.dev.ole.kuali.org','upload','data4OLE',1.0,'39505551-A659-A8ED-F020-D9D1E3552195','Y',2.0)
/
