--
-- Copyright 2010-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE PUR_VNDR_ALIAS_T DROP STORAGE
/
INSERT INTO PUR_VNDR_ALIAS_T (VNDR_ALIAS_NM,VNDR_HDR_GNRTD_ID,VNDR_DTL_ASND_ID,OBJ_ID,VER_NBR,DOBJ_MAINT_CD_ACTV_IND,OLE_ALIAS_TYP_ID,OLE_PUR_VNDR_ALIAS_ID)
  VALUES ('ABB',1000.0,0.0,'6E889BC2-5430-CC36-1810-F227D343902A',1.0,'Y',3.0,1000.0)
/
INSERT INTO PUR_VNDR_ALIAS_T (VNDR_ALIAS_NM,VNDR_HDR_GNRTD_ID,VNDR_DTL_ASND_ID,OBJ_ID,VER_NBR,DOBJ_MAINT_CD_ACTV_IND,OLE_ALIAS_TYP_ID,OLE_PUR_VNDR_ALIAS_ID)
  VALUES ('DKA',1009.0,0.0,'B312AD22-472A-80EB-17E4-36E965430499',1.0,'Y',3.0,1000.0)
/
INSERT INTO PUR_VNDR_ALIAS_T (VNDR_ALIAS_NM,VNDR_HDR_GNRTD_ID,VNDR_DTL_ASND_ID,OBJ_ID,VER_NBR,DOBJ_MAINT_CD_ACTV_IND,OLE_ALIAS_TYP_ID,OLE_PUR_VNDR_ALIAS_ID)
  VALUES ('YBP',12106.0,0.0,'2FCAD9C7-615C-5668-22AF-4414BF82ABCC',1.0,'Y',3.0,1000.0)
/
INSERT INTO PUR_VNDR_ALIAS_T (VNDR_ALIAS_NM,VNDR_HDR_GNRTD_ID,VNDR_DTL_ASND_ID,OBJ_ID,VER_NBR,DOBJ_MAINT_CD_ACTV_IND,OLE_ALIAS_TYP_ID,OLE_PUR_VNDR_ALIAS_ID)
  VALUES ('HARRAS',12111.0,0.0,'0BB1B34D-683F-A144-3DB4-58A4AA3C8995',1.0,'Y',3.0,1007.0)
/
