--
-- Copyright 2010-2013 The Kuali Foundation
--
-- Licensed under the Educational Community License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.opensource.org/licenses/ecl2.php
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

TRUNCATE TABLE PUR_VNDR_CONTR_ORG_T DROP STORAGE
/
INSERT INTO PUR_VNDR_CONTR_ORG_T (VNDR_CONTR_GNRTD_ID,FIN_COA_CD,ORG_CD,OBJ_ID,VER_NBR,VNDR_CTRPO_LMT_AMT,VNDR_CONTR_EXCL_IND,DOBJ_MAINT_CD_ACTV_IND)
  VALUES (1000.0,'BL','ACTR','841C5AF9-D6FD-DF68-9AE1-DB4C45A6B1AA',2.0,500.0,'N','Y')
/
INSERT INTO PUR_VNDR_CONTR_ORG_T (VNDR_CONTR_GNRTD_ID,FIN_COA_CD,ORG_CD,OBJ_ID,VER_NBR,VNDR_CTRPO_LMT_AMT,VNDR_CONTR_EXCL_IND,DOBJ_MAINT_CD_ACTV_IND)
  VALUES (1017.0,'BA','ACAC','458FA7F0-39BF-5B5C-3972-B21CA40C6878',2.0,1000.0,'N','Y')
/
INSERT INTO PUR_VNDR_CONTR_ORG_T (VNDR_CONTR_GNRTD_ID,FIN_COA_CD,ORG_CD,OBJ_ID,VER_NBR,VNDR_CTRPO_LMT_AMT,VNDR_CONTR_EXCL_IND,DOBJ_MAINT_CD_ACTV_IND)
  VALUES (1020.0,'BL','AAAM','F7C050B6-C87C-0F82-2506-1F0730AD89EF',2.0,500.0,'N','Y')
/
INSERT INTO PUR_VNDR_CONTR_ORG_T (VNDR_CONTR_GNRTD_ID,FIN_COA_CD,ORG_CD,OBJ_ID,VER_NBR,VNDR_CTRPO_LMT_AMT,VNDR_CONTR_EXCL_IND,DOBJ_MAINT_CD_ACTV_IND)
  VALUES (2003.0,'BL','AAAM','69B36135-3D52-98A4-3B96-E5EDE14BB985',5.0,1001.0,'N','Y')
/
INSERT INTO PUR_VNDR_CONTR_ORG_T (VNDR_CONTR_GNRTD_ID,FIN_COA_CD,ORG_CD,OBJ_ID,VER_NBR,VNDR_CTRPO_LMT_AMT,VNDR_CONTR_EXCL_IND,DOBJ_MAINT_CD_ACTV_IND)
  VALUES (2009.0,'BL','ACAD','3961C8C3-3579-D7FB-F207-57B6A9720E39',1.0,1000.0,'N','Y')
/
