#!/bin/bash
#
# Output from this script gets logged to /var/log/cloud-init.log
#

#
# If you change this script it will not take affect on newly spun up EC2 instances until:
# 1 - You publish and release another version of kuali-ec2
# 2 - You make the kuali-example project point to the new version of kuali-ec2
#
#
# If you only change what the following commands do behind the scenes,
# ie you add/update/remove plugin executions or alter the Ant scripting,
# no further action is required.  The changes will be automatically
# picked up and executed the next time an environment is spun up
#

set -xe
rm -rf /root/kuali-ec2
svn co https://svn.kuali.org/repos/foundation/trunk/kuali-ec2 /root/kuali-ec2
cd /root/kuali-ec2
MVN=/opt/asf/mvn/bin/mvn
$MVN clean install
PROFILES="tomcat,${tomcat.version},medium"
ARGS="-Djdk.version=${jdk.version} -Dheap.max=${heap.max} -Dheap.min=${heap.min} -Dheap.maxPermSize=${heap.maxPermSize}"
$MVN clean process-resources -P$PROFILES $ARGS
$MVN clean process-resources -Pappdynamics
