#!/bin/bash

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)

source $MY_DIR/../common/functions.sh

usage() { echo "Usage: $ME message" 1>&2; exit 1;} 

MESSAGE=$1

check_not_blank MESSAGE $MESSAGE

svn commit -m "$MESSAGE" $MY_DIR/../../../jenkins/master.zip.gpg
