#!/bin/bash
#
# Copyright 2004-2014 The Kuali Foundation
#
# Licensed under the Educational Community License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.opensource.org/licenses/ecl2.php
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function install_firefox {

  # 14.0.1, 27.0.1
  VERSION=$1
  
  # 14, 27
  SHORT_VERSION=$2

  GROUP_ID=org.mozilla
  ARTIFACT_ID=firefox
  CLASSIFIER=linux-x86_64_en-US
  TYPE=bz2
  
  echo "install   -> firefox $VERSION"
  
  # Setup command line args
  MAVEN_ARGS="$GROUP_ID $ARTIFACT_ID $VERSION --classifier=$CLASSIFIER --type=$TYPE"
  
  # Example URL:
  # http://maven.kuali.org/external/org/mozilla/firefox/27.0.1/firefox-27.0.1-linux-x86_64_en-US.bz2
  # Cache firefox.bz2 from Kuali's S3 maven repo
  $MY_DIR/../common/m2download $QUIET_FLAG $MAVEN_ARGS --repo="http://maven.kuali.org/external"
  
  # Calculate the path to the locally cached copy of the compressed file
  LOCAL_MAVEN_REPO_FILE=$($MY_DIR/../common/m2path $MAVEN_ARGS)
  
  # /usr/local/firefox/firefox-27.0.1
  FIREFOX_DIR=$FIREFOX_BASEDIR/$ARTIFACT_ID-$VERSION

  # /usr/local/firefox/firefox27
  FIREFOX_LINK=$FIREFOX_BASEDIR/firefox$SHORT_VERSION

  # /usr/bin/firefox27
  FIREFOX_USR_BIN=/usr/bin/firefox$SHORT_VERSION
  
  # Purge everything related to the currently installed version
  execute_quietly "rm -rf $FIREFOX_BASEDIR/firefox $FIREFOX_DIR $FIREFOX_LINK $FIREFOX_USR_BIN"
  
  # Unpack the bz2 into /usr/local/firefox
  execute_quietly "tar -xjvf $LOCAL_MAVEN_REPO_FILE --directory $FIREFOX_BASEDIR"

  # Move /usr/local/firefox/firefox -> /usr/local/firefox/firefox27.0.1
  execute_quietly "mv $FIREFOX_BASEDIR/firefox $FIREFOX_DIR"
  
  # create /usr/local/firefox/firefox27 -> /usr/local/firefox/firefox-27.0.1
  execute_quietly "ln -s $FIREFOX_DIR $FIREFOX_LINK"

  # create /usr/bin/firefox27 -> /usr/local/firefox/firefox27/firefox
  execute_quietly "ln -s $FIREFOX_LINK/firefox $FIREFOX_USR_BIN"

}

function install_maven {

  # 3.0.5, 3.1.0, 3.2.1
  VERSION=$1
  
  # 30, 31, 32
  SHORT_VERSION=$2
  
  GROUP_ID=org.apache.maven
  ARTIFACT_ID=apache-maven
  CLASSIFIER=bin
  TYPE=zip
  
  echo "install   -> maven $VERSION"
  
  # Setup command line args
  MAVEN_ARGS="$GROUP_ID $ARTIFACT_ID $VERSION --classifier=$CLASSIFIER --type=$TYPE"
  
  # Cache apache-maven.zip from Maven Central
  $MY_DIR/../common/m2download $QUIET_FLAG $MAVEN_ARGS
  
  # Calculate the path to the locally cached copy of the zip
  LOCAL_MAVEN_ZIP_FILE=$($MY_DIR/../common/m2path $MAVEN_ARGS)

  # /usr/maven/apache-maven-3.2.1
  MAVEN_DIR=$MAVEN_BASEDIR/$ARTIFACT_ID-$VERSION

  # /usr/maven/mvn32
  MAVEN_LINK=$MAVEN_BASEDIR/mvn$SHORT_VERSION

  # /usr/bin/mvn32
  MAVEN_USR_BIN=/usr/bin/mvn$SHORT_VERSION

  # Remove any previous traces of this version of Maven
  execute_quietly "rm -rf $MAVEN_DIR $MAVEN_LINK $MAVEN_USR_BIN"

  # Unpack the zip file into /usr/maven
  execute_quietly "unzip $LOCAL_MAVEN_ZIP_FILE -d $MAVEN_BASEDIR"
  
  # /usr/maven/mvn32
  execute_quietly "ln -s $MAVEN_DIR $MAVEN_LINK"
  
  # The actual Maven binary
  # /usr/maven/mvn32/bin/mvn  
  MAVEN_TARGET=$MAVEN_BASEDIR/mvn$SHORT_VERSION/bin/mvn

  # This is obviously overkill, but there was a screwy permissions issue of some kind for a file somewhere under the Maven install that was causing issues
  # Should troubleshoot the issue and only 755 the files that really need to be executable
  execute_quietly "chmod -R 755 $MAVEN_DIR"
  
  # Create symbolic links that only change when Maven's minor version does ie 3.1 -> 3.2
  # 3.2.2 replaces 3.2.1, and 3.1.1 replaces 3.1.0, etc
  execute_quietly "ln -s $MAVEN_TARGET $MAVEN_LINK"
  execute_quietly "ln -s $MAVEN_TARGET $MAVEN_USR_BIN"
  
}

function install_default_maven {
  MAVEN_ABBR=$1

  echo "install   -> default maven mvn$MAVEN_ABBR"

  MAVEN_TARGET=$MAVEN_BASEDIR/mvn$MAVEN_ABBR/bin/mvn
  MAVEN_USR_BIN=/usr/bin/mvn

  rm -rf $MAVEN_USR_BIN
  ln -s $MAVEN_TARGET $MAVEN_USR_BIN
  chmod 755 $MAVEN_BASEDIR
}

function install_default_firefox {
  MAVEN_ABBR=$1

  echo "install   -> default maven mvn$MAVEN_ABBR"

  MAVEN_TARGET=$MAVEN_BASEDIR/mvn$MAVEN_ABBR/bin/mvn
  MAVEN_USR_BIN=/usr/bin/mvn

  rm -rf $MAVEN_USR_BIN
  ln -s $MAVEN_TARGET $MAVEN_USR_BIN
  chmod 755 $MAVEN_BASEDIR
}

# Make sure /usr/bin/java points to JDK7  
function configure_java {

  echo "configure -> default java"
  echo "jenkins   -> master :: $JENKINS_MASTER"
  
  # the default /root/.bashrc that ships with 12.04 automatically imports /root/.bash_aliases
  ROOT_ALIASES=/root/.bash_aliases
  echo "JAVA_HOME=/usr/java/jdk7"                        >  $ROOT_ALIASES
  echo "PATH=\$JAVA_HOME/bin:$PATH:."                    >> $ROOT_ALIASES
  echo "MAVEN_OPTS=\"$MAVEN_OPTS\""                      >> $ROOT_ALIASES
  echo "JENKINS_MASTER=\"$JENKINS_MASTER\""              >> $ROOT_ALIASES
  echo "export JAVA_HOME PATH MAVEN_OPTS JENKINS_MASTER" >> $ROOT_ALIASES

  # remove java related links from /usr/bin/java and replace them with symbolic links to jdk7
  execute_quietly "rm -rf /usr/bin/java"
  execute_quietly "ln -s /usr/java/jdk7/bin/java /usr/bin/java"
  
  execute_quietly "rm -rf /usr/bin/javac"
  execute_quietly "ln -s /usr/java/jdk7/bin/javac /usr/bin/javac"

  execute_quietly "rm -rf /usr/bin/javadoc"
  execute_quietly "ln -s /usr/java/jdk7/bin/javadoc /usr/bin/javadoc"
}

function configure_secrets {

  # Extract secrets into /root/.ssh
  echo "configure -> secrets"
  GPG_ENCRYPTED=$MY_DIR/secrets.zip.gpg
  GPG_DECRYPTED=$MY_DIR/secrets.zip
  decrypt_file $GPG_ENCRYPTED $GPG_DECRYPTED
  execute_quietly "unzip -o $GPG_DECRYPTED -d /root"
  execute_quietly "rm $GPG_DECRYPTED"

  # Setup GPG
  GPG_KEY=/root/.ssh/jcaddel.gpg.private
  rm -rf /root/.gnupg
  execute_quietly "gpg --allow-secret-key-import --import $GPG_KEY"
  
  # setup maven
  execute_quietly "mkdir -p /root/.m2/repository"  
  execute_quietly "mv /root/.ssh/settings.xml /root/.m2/settings.xml"
  
}

function configure_subversion {

  echo "configure -> subversion"
  SVN_BASEDIR=/root/.subversion
  SVN_SERVERS=$SVN_BASEDIR/servers
  
  rm -rf $SVN_BASEDIR; mkdir -p $SVN_BASEDIR
  echo "[global]"                      >  $SVN_SERVERS
  echo "store-plaintext-passwords=yes" >> $SVN_SERVERS
  
}

function touch_subversion_repo {

  SVN_REPO=$1
  check_not_blank SVN_REPO $SVN_REPO
  
  SVN_TOUCH_URL="https://svn.kuali.org/repos/$SVN_REPO/sandbox/kuali-devops/temp/auth-check/touch"
  echo "touch     -> svn:$SVN_REPO - [$SVN_TOUCH_URL]"

  SVN_USERNAME=jcaddel
  SVN_PASSWORD_FILE="/root/.ssh/subversion.password"
  SVN_PASSWORD=$(<$SVN_PASSWORD_FILE)
  check_not_blank SVN_PASSWORD $SVN_PASSWORD
  SVN_AUTH="--username=$SVN_USERNAME --password=$SVN_PASSWORD"
  # the message can't have spaces in it
  SVN_MESSAGE="automated-auth-check"
  execute_quietly "svn mkdir  $SVN_TOUCH_URL --message $SVN_MESSAGE --parents $SVN_AUTH"
  execute_quietly "svn delete $SVN_TOUCH_URL --message $SVN_MESSAGE"
  
}

function touch_subversion_repos {

  touch_subversion_repo foundation
  touch_subversion_repo rice
  touch_subversion_repo student
  touch_subversion_repo ole
  touch_subversion_repo mobility
  touch_subversion_repo kpme
  
}


function check_args {
  check_not_blank JENKINS_MASTER $JENKINS_MASTER
  check_not_blank GPG_PASSPHRASE $GPG_PASSPHRASE
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/../common/functions.sh

usage() { echo "Usage: $ME [-h] [-q] [-m \"-Xmx2g -XX:MaxPermSize=256m\"] [-p \"package1 package2 package3\"] master password" 1>&2; exit 1; }

QUIET=false
PACKAGES="subversion git graphviz ant"
MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=256m"
while getopts hqm:p: flag; do
  case $flag in
    h)
      usage;
      ;;
    q)
      QUIET=true;
      ;;
    p)
      PACKAGES="$PACKAGES $OPTARG";
      ;;
    m)
      MAVEN_OPTS="$OPTARG";
      ;;
    ?)
      usage;
      exit;
      ;;
  esac
done

shift $(( OPTIND - 1 ));

JENKINS_MASTER=$1
GPG_PASSPHRASE=$2

check_args

QUIET_FLAG=""
if [ "$QUIET" == "true" ]; then
  QUIET_FLAG="-q"
fi

MAVEN_BASEDIR=/usr/maven
FIREFOX_BASEDIR="/usr/local/firefox"

execute_quietly "mkdir -p $MAVEN_BASEDIR"
execute_quietly "mkdir -p $FIREFOX_BASEDIR"


configure_secrets
install_packages
install_maven 3.0.5 30
install_maven 3.1.0 31
install_maven 3.2.1 32
install_default_maven 32
install_firefox 14.0.1 14
install_firefox 27.0.1 27
configure_java
configure_subversion

#
# SVN caches and then looks up credentials based on the hostname + hostname hash
#
# eg for jcaddel/<password> @ https://svn.kuali.org
#
# SVN creates the file -> /root/.subversion/auth/svn.simple/7bde6701d85dbc4080b5213025d59913
# ...
# <https://svn.kuali.org:443> SVN Login
# ...
#
# This means we only need to cache one set of credentials for all repo's at kuali
# That set of credentials will then work transparently for all repo's 
#
echo "UNCOMMENT THE NEXT LINE!!!"
# touch_subversion_repo foundation
# touch_subversion_repos
