#!/bin/bash
#
# Copyright 2004-2014 The Kuali Foundation
#
# Licensed under the Educational Community License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.opensource.org/licenses/ecl2.php
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#



function check_args {
  check_not_blank JENKINS_MASTER $JENKINS_MASTER
}

function slave_shutdown_scripting {
  
  echo "configure -> jenkins:slave:shutdown:rsync"
  
  EC2SLAVE_DST_DIR=/usr/share/ec2slave
  rm -rf $EC2SLAVE_DST_DIR; mkdir -p $EC2SLAVE_DST_DIR;
  
  EC2SLAVE_SRC_DIR=$MY_DIR/slave
  
  EC2SLAVE_SRC=$EC2SLAVE_SRC_DIR/ec2slave
  EC2SLAVE_DST=/etc/init.d/ec2slave
  cp $EC2SLAVE_SRC $EC2SLAVE_DST

  EXCLUDES_SRC=$EC2SLAVE_SRC_DIR/rsync.excludes
  EXCLUDES_DST=$EC2SLAVE_DST_DIR/rsync.excludes
  cp $EXCLUDES_SRC $EXCLUDES_DST

  COPY_REPO_SRC=$EC2SLAVE_SRC_DIR/copy_repo_to_master.sh
  COPY_REPO_DST=$EC2SLAVE_DST_DIR/copy_repo_to_master.sh
  cp $COPY_REPO_SRC $COPY_REPO_DST
  
  chmod 755 $COPY_REPO_DST

  execute_quietly "update-rc.d -f ec2slave remove"
  execute_quietly "update-rc.d    ec2slave defaults"

}

function install_mysql_server {

  echo "remove    -> mysql-server"
  # Remove all traces of MySQL
  execute_quietly "apt-get remove mysql-server -y"
  execute_quietly "apt-get purge  mysql-server -y"
  execute_quietly "apt-get autoremove -y"

  echo "install   -> mysql-server"
  # Setup the MySQL install so it won't prompt for a password
  MYSQL_ROOT_PASSWORD=password
  debconf-set-selections <<< "mysql-server mysql-server/root_password       password $MYSQL_ROOT_PASSWORD"
  debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $MYSQL_ROOT_PASSWORD"
   
  # Install MySQL with no prompts  
  execute_quietly "apt-get install mysql-server -y"
  
  # Remove the password for the root user
  execute_quietly "mysqladmin -u root -p$MYSQL_ROOT_PASSWORD password ''"
   
}

function copy_repo_from_master {

  M2_REPO=/root/.m2/repository
  mkdir -p $M2_REPO
  REMOTE_REPO=$JENKINS_MASTER:$M2_REPO
  echo "rsync     -> $REMOTE_REPO"
  echo "rsync     -> start -> $(date)"
  execute_quietly "rsync -av --stats root@$REMOTE_REPO/ $M2_REPO" 
  echo "rsync     -> stop  -> $(date)"
  
}

function copy_repo_from_amazon {

  M2_REPO=/root/.m2/repository
  mkdir -p $M2_REPO
  echo "copy      -> s3://maven.kuali.org/release"
  echo "start     -> $(date)"
  MAVEN_POM="$BASEDIR/META-INF/maven/${project.groupId}/${project.artifactId}/pom.xml"
  MAVEN_ARGS="$MAVEN_ARGS -f $MAVEN_POM"
  MAVEN_ARGS="$MAVEN_ARGS initialize -Pupdate"
  MAVEN_ARGS="$MAVEN_ARGS -Dorg.slf4j.simpleLogger.log.org.kuali.maven.wagon=warn"
  MAVEN="mvn $MAVEN_ARGS"
  execute_quietly "$MAVEN"
  echo "stop      -> $(date)"
  
}

function enable_root_ssh {
  echo "enable    -> root ssh"
  SED="sed -i -e 's/disable_root: 0/disable_root: 1/g' /etc/cloud/cloud.cfg"
  execute_quietly "$SED"
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/../common/functions.sh

usage() { echo "Usage: $ME [-h] [-q] master" 1>&2; exit 1; }

QUIET=false
while getopts hqm: flag; do
  case $flag in
    h)
      usage;
      ;;
    q)
      QUIET="true";
      ;;
    ?)
      usage;
      exit;
      ;;
  esac
done

shift $(( OPTIND - 1 ));

JENKINS_MASTER=$1

check_args

slave_shutdown_scripting
install_mysql_server
copy_repo_from_master
enable_root_ssh
