#!/bin/bash
#
# Copyright 2004-2014 The Kuali Foundation
#
# Licensed under the Educational Community License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.opensource.org/licenses/ecl2.php
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function check_args {
  check_not_blank JENKINS_MASTER $JENKINS_MASTER
  check_not_blank GPG_PASSPHRASE $GPG_PASSPHRASE
}

# connect to a remote server, zip jenkins config, and scp it to the local machine
function encrypt_config {

  ZIP_FILE="$MY_DIR/../../../jenkins/master.zip
  GPG_FILE="$ZIP_FILE.gpg"
  cd /home/tomcat7
  zip -r $ZIP_FILE .jenkins -x '**/plugins/**' '**/workspace/**' '**/config-history/**'"
  encrypt_file $ZIP_FILE $GPG_FILE
  
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/../common/functions.sh

usage() { echo "Usage: $ME [-h] [-q] password" 1>&2; exit 1; }

encrypt_config
