#!/bin/bash

function encrypt_config {
  GPG_DECRYPTED=$MY_DIR/../../../jenkins/master.zip
  GPG_ENCRYPTED=$GPG_DECRYPTED.gpg
  echo "zip     -> master config"
  cd /home/tomcat7
  zip -q -r $GPG_DECRYPTED .jenkins -x **/plugins/** **/config-history/** **/workspace/** **/builds/** **/lastStable/** **/lastSuccessful/**
  echo "encrypt -> master config"
  encrypt_file $GPG_DECRYPTED $GPG_ENCRYPTED
  execute_quietly "rm $GPG_DECRYPTED"
}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/../common/functions.sh
usage() { echo "Usage: $ME password" 1>&2; exit 1; }
QUIET=true
GPG_PASSPHRASE=$1
check_not_blank GPG_PASSPHRASE $GPG_PASSPHRASE

encrypt_config
