#!/bin/bash

QUIET=$1

if [ "$QUIET" == "-q" ]; then
  QUIET="true"
fi

execute_quietly "rm -rf /var/lib/gems/1.9.1 /root/.gem"

execute_quietly "gem install --no-rdoc --no-ri selenium-webdriver -v 2.35.1"
execute_quietly "gem install --no-rdoc --no-ri watir-webdriver -v 0.6.4"
execute_quietly "gem install --no-rdoc --no-ri headless -v 1.0.1"

#gem install --no-rdoc --no-ri watir-webdriver -v 0.6.8
#gem install --no-rdoc --no-ri selenium-webdriver -v 2.40.0
