#!/bin/bash

function install_ks_sambal_gems {

  BUNDLER_VERSION=1.6.0
  
  echo "checkout  -> sambal trunk"
  execute_quietly "svn co https://svn.kuali.org/repos/student/test/functional-automation/sambal/trunk $KS_SAMBAL_DIR"
  execute_quietly "cd $KS_SAMBAL_DIR"
  echo "install   -> gem :: bundler :: $BUNDLER_VERSION"
  execute_quietly "gem install --include-dependencies --no-rdoc --no-ri --version $BUNDLER_VERSION bundler"
  echo "install   -> gems"
  execute_quietly "bundle install"
  
}

function validate_cucumber {

  echo "validate  -> cucumber"
  execute_quietly "cd $KS_SAMBAL_DIR"
  execute_quietly "cucumber -r features -t @should_not_match_anything ."
  
}

function install_gem {

  GEM_ARTIFACT_ID=$1
  GEM_VERSION=$2
  echo "install   -> gem $GEM_ARTIFACT_ID :: $GEM_VERSION"    
  execute_quietly "gem install --no-rdoc --no-ri --version $GEM_VERSION $GEM_ARTIFACT_ID"
  
}


MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/../common/functions.sh

QUIET=$1
if [ "$QUIET" == "-q" ]; then
  QUIET=true
fi

echo "purge     -> ruby gems"
rm -rf /var/lib/gems/1.9.1 /root/.gem

# Previous versions from ci.rice
# SELENIUM_WEBDRIVER_VERSION=2.35.1
# WATIR_WEBDRIVER_VERSION=0.6.4

# Latest versions
SELENIUM_WEBDRIVER_VERSION=2.40.0
WATIR_WEBDRIVER_VERSION=0.6.8
HEADLESS_VERSION=1.0.1

#install_gem headless           $HEADLESS_VERSION
#install_gem selenium-webdriver $SELENIUM_WEBDRIVER_VERSION
#install_gem watir-webdriver    $WATIR_WEBDRIVER_VERSION
#install_ks_sambal_gems
KS_SAMBAL_DIR=/ssd/sambal-trunk

  
