#!/bin/bash

set -e

apt-get update -y
apt-get --purge remove ruby-rvm -y
rm -rf /usr/share/ruby-rvm /etc/rvmrc /etc/profile.d/rvm.sh

apt-get install ruby1.9.3 libxslt1-dev libxml2-dev libyaml-dev -y

