#!/bin/bash

set -e

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/../common/functions.sh

QUIET=$1
if [ "$QUIET" == "-q" ]; then
  QUIET="true"
fi

echo "purge     -> ruby gems"
execute_quietly "rm -rf /var/lib/gems/1.9.1 /root/.gem"

echo "install   -> ruby gems"

SELENIUM_WEBDRIVER_VERSION=2.35.1
WATIR_WEBDRIVER_VERSION=0.6.4
HEADLESS_VERSION=1.0.1
#SELENIUM_WEBDRIVER_VERSION=2.40.0
#WATIR_WEBDRIVER_VERSION=0.6.8

execute_quietly "gem install --no-rdoc --no-ri selenium-webdriver -v $SELENIUM_WEBDRIVER_VERSION"
execute_quietly "gem install --no-rdoc --no-ri watir-webdriver -v $WATIR_WEBDRIVER_VERSION"
execute_quietly "gem install --no-rdoc --no-ri headless -v $HEADLESS_VERSION"
