#!/bin/bash
#
# Copyright 2004-2014 The Kuali Foundation
#
# Licensed under the Educational Community License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.opensource.org/licenses/ecl2.php
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

function check_args {
  check_not_blank JENKINS_MASTER $JENKINS_MASTER
  check_not_blank GPG_PASSPHRASE $GPG_PASSPHRASE
}

# connect to a remote server, zip jenkins config, and scp it to the local machine
function scp_zip_file {

  ZIP_FILE="master.zip"
  SERVER_ZIP="/mnt/$ZIP_FILE"
  LOCAL_ZIP="$MY_DIR/../../../jenkins/$ZIP_FILE"
  GPG_FILE="$LOCAL_ZIP.gpg"
  
  SSH1="rm -f $SERVER_ZIP"
  SSH2="cd /home/tomcat7"
  #SSH3="zip -qq -r $SERVER_ZIP .jenkins -x '**/plugins/**' '**/workspace/**'"
  #SSH3="zip -qq -r $SERVER_ZIP .jenkins -x '**/plugins/**' '**/jobs/**' '**/config-history/**'"
  SSH3="zip -qq -r $SERVER_ZIP .jenkins -x '**/plugins/**' '**/workspace/**' '**/config-history/**'"
  SSH="$SSH1; $SSH2; $SSH3"
  SSH="ssh root@$JENKINS_MASTER $SSH"

  echo "zip     -> root@$JENKINS_MASTER:$SERVER_ZIP"
  execute_quietly "$SSH"
  echo "scp     -> root@$JENKINS_MASTER:$SERVER_ZIP"
  execute_quietly "scp root@$JENKINS_MASTER:$SERVER_ZIP $LOCAL_ZIP"
  echo "create  -> $(basename $GPG_FILE)"
  encrypt_file $LOCAL_ZIP $GPG_FILE
  execute_quietly "rm $LOCAL_ZIP"

}

MY_DIR="$( cd "$( dirname "$0" )" && pwd )"
ME=$(basename $0)
source $MY_DIR/../common/functions.sh

usage() { echo "Usage: $ME [-h] [-q] master password true/false" 1>&2; exit 1; }

JENKINS_MASTER=$1
GPG_PASSPHRASE=$2
QUIET=$3

check_args

scp_zip_file
